UPDATE `creature_template_wdb_locale` SET `Title`='Corrección de logros, tareas, etc.' WHERE (`ID`='600022') AND (`Locale`='ruRU');
UPDATE `creature_text` SET `Text`='Hola! Quiero advertirte que puedo reparar no todos los logros, misiones, etc.' WHERE (`Entry`='600022') AND (`Text`='Hello, $n! I want to warn you I can repair not all bugged and not working achievements, quests etc.');
UPDATE `creature_text` SET `Text`='DIGA LA PRUEBA' WHERE (`Entry`='600022') AND (`Text`='SAY TEST');
UPDATE `creature_text_back` SET `Text`='¡Hola! Quiero advertirte que puedo reparar no todos los logros, misiones, etc.' WHERE (`Entry`='600022') AND (`GroupID`='0') AND (`ID`='0');
UPDATE `creature_text_back` SET `Text`='DIGA LA PRUEBA' WHERE (`Entry`='600022') AND (`GroupID`='1') AND (`ID`='0');
UPDATE `gossip_menu_option` SET `OptionText`='Paradise Lost (questID: 39718)' WHERE (`MenuID`='600022') AND (`OptionIndex`='14');
UPDATE `gossip_menu_option` SET `OptionText`='Montaña solitaria (questID: 39733)' WHERE (`MenuID`='600022') AND (`OptionIndex`='15');
UPDATE `gossip_menu_option` SET `OptionText`='Bosque tranquilo (questID: 39731)' WHERE (`MenuID`='600022') AND (`OptionIndex`='16');
UPDATE `gossip_menu_option` SET `OptionText`='Tormenheim H (questID: 39864)' WHERE (`MenuID`='600022') AND (`OptionIndex`='17');
UPDATE `gossip_menu_option` SET `OptionText`='Tormenheim (questID: 39735)' WHERE (`MenuID`='600022') AND (`OptionIndex`='18');
UPDATE `gossip_menu_option` SET `OptionText`='Razones para lo invencible (logro ID: 4625)' WHERE (`MenuID`='600022') AND (`OptionIndex`='19');
UPDATE `gossip_menu_option` SET `OptionText`='OPCIÓN DE MENÚ DE PRUEBA - SIN ACCIONES' WHERE (`MenuID`='600022') AND (`OptionIndex`='20');
UPDATE `gossip_menu_option` SET `OptionText`='Gran Yak de viaje (logro ID: 7386)' WHERE (`MenuID`='600022') AND (`OptionIndex`='0');
UPDATE `gossip_menu_option` SET `OptionText`='<- Volver al menú principal' WHERE (`MenuID`='600123') AND (`OptionIndex`='0');
UPDATE `gossip_menu_option` SET `OptionText`='Menú de misiones' WHERE (`MenuID`='600022') AND (`OptionIndex`='31');
UPDATE `gossip_menu_option` SET `OptionText`='Logros' WHERE (`MenuID`='600022') AND (`OptionIndex`='32');
UPDATE `gossip_menu_option` SET `OptionText`='Riendas del caballo sin cabeza (logroID: 980)' WHERE (`MenuID`='600022') AND (`OptionIndex`='27');
UPDATE `gossip_menu_option` SET `OptionText`='Precursor de la llama (logro ID: 11425)' WHERE (`MenuID`='600022') AND (`OptionIndex`='26');
UPDATE `gossip_menu_option` SET `OptionText`='Objetos' WHERE (`MenuID`='600022') AND (`OptionIndex`='30');
UPDATE `gossip_menu_option` SET `OptionText`='Si no puedes completar: Crystal Fury (questID: 39487)' WHERE (`MenuID`='600022') AND (`OptionIndex`='29');
UPDATE `gossip_menu_option` SET `OptionText`='Si no puedes completar: llegar a terreno elevado (questID: 38909)' WHERE (`MenuID`='600022') AND (`OptionIndex`='28');
UPDATE `gossip_menu_option` SET `OptionText`='<- Volver al menú principal' WHERE (`MenuID`='600124') AND (`OptionIndex`='0');
UPDATE `gossip_menu_option` SET `OptionText`='Cristal resonante Qiraji rojo (logro ID: 980)' WHERE (`MenuID`='600022') AND (`OptionIndex`='25');
UPDATE `gossip_menu_option` SET `OptionText`='Ram de la Fiesta de la Cerveza Swift (logro ID: 3496)' WHERE (`MenuID`='600022') AND (`OptionIndex`='24');
UPDATE `gossip_menu_option` SET `OptionText`='Grand Hop Festival Kodo (logro ID: 3496)' WHERE (`MenuID`='600022') AND (`OptionIndex`='23');
UPDATE `gossip_menu_option` SET `OptionText`='Chiflado (achievementID: 2336)' WHERE (`MenuID`='600022') AND (`OptionIndex`='21');
UPDATE `gossip_menu_option` SET `OptionText`='Reputación de Ala Abisal. Si completa la misión: Aliado del Ala Abisal (factionID: 1015)' WHERE (`MenuID`='600022') AND (`OptionIndex`='22');
UPDATE `gossip_menu_option` SET `OptionText`='Si desea mostrar el menú y completar el logro de las monturas que no funcionan (como Grand Expedition Yak), debe sentarse en esta montura.' WHERE (`MenuID`='600022') AND (`OptionIndex`='13');
UPDATE `gossip_menu_option` SET `OptionText`='Riendas del señor del cuervo (logro ID: 883)' WHERE (`MenuID`='600022') AND (`OptionIndex`='12');
UPDATE `gossip_menu_option` SET `OptionText`='Eternal Sands Wanderer (logro ID: 5767)' WHERE (`MenuID`='600022') AND (`OptionIndex`='11');
UPDATE `gossip_menu_option` SET `OptionText`='Pepe Al\'ara (achievementID: 2097)' WHERE (`MenuID`='600022') AND (`OptionIndex`='10');
UPDATE `gossip_menu_option` SET `OptionText`='Esto no es una motocicleta, bebé (logro ID: 2097)' WHERE (`MenuID`='600022') AND (`OptionIndex`='9');
UPDATE `gossip_menu_option` SET `OptionText`='Esto no es una motocicleta, bebé (logro ID: 2097)' WHERE (`MenuID`='600022') AND (`OptionIndex`='8');
UPDATE `gossip_menu_option` SET `OptionText`='Mamut de la tundra del viajero (logro ID: 2078)' WHERE (`MenuID`='600022') AND (`OptionIndex`='7');
UPDATE `gossip_menu_option` SET `OptionText`='Mamut de la tundra del viajero (logro ID: 2078)' WHERE (`MenuID`='600022') AND (`OptionIndex`='6');
UPDATE `gossip_menu_option` SET `OptionText`='Mamut lanudo (logro ID: 2077)' WHERE (`MenuID`='600022') AND (`OptionIndex`='5');
UPDATE `gossip_menu_option` SET `OptionText`='Mamut lanudo (logro ID: 2077)' WHERE (`MenuID`='600022') AND (`OptionIndex`='4');
UPDATE `gossip_menu_option` SET `OptionText`='Frasco de arenas (logro ID: 5749)' WHERE (`MenuID`='600022') AND (`OptionIndex`='3');
UPDATE `gossip_menu_option_locale` SET `Locale`='esES', `OptionText`='Alas abisales: para aquellos que realizaron: Aliado de las alas abisales (ID de facción: 1015)' WHERE (`MenuID`='600022') AND (`ID`='22') AND (`Locale`='ruRU');
UPDATE `gossip_menu_option_locale` SET `Locale`='esES', `OptionText`='Para mostrar el menú y obtener un logro previamente inviable para la montura, debes sentarte en la montura para la que dan el logro.' WHERE (`MenuID`='600022') AND (`ID`='13') AND (`Locale`='ruRU');
UPDATE `gossip_menu_option_locale` SET `Locale`='esES', `OptionText`='Logros' WHERE (`MenuID`='600022') AND (`ID`='32') AND (`Locale`='ruRU');
UPDATE `gossip_menu_option_locale` SET `Locale`='esES', `OptionText`='Artículos' WHERE (`MenuID`='600022') AND (`ID`='30') AND (`Locale`='ruRU');
UPDATE `gossip_menu_option_locale` SET `Locale`='esES', `OptionText`='Menú de trabajo' WHERE (`MenuID`='600022') AND (`ID`='31') AND (`Locale`='ruRU');
UPDATE `gossip_menu_option_locale` SET `Locale`='esES', `OptionText`='Crystal Fury (questID: 39487)' WHERE (`MenuID`='600022') AND (`ID`='29') AND (`Locale`='ruRU');
UPDATE `gossip_menu_option_locale` SET `Locale`='esES', `OptionText`='Para aquellos que no pueden tomarlo: Lejos del peligro (questID: 38909)' WHERE (`MenuID`='600022') AND (`ID`='28') AND (`Locale`='ruRU');
UPDATE `creature_template_wdb` SET `Title`='Repara logros, misiones, etc.' WHERE (`Entry`='600022');
UPDATE `creature_template_wdb_locale` SET `Locale`='esES', `Name1`='De\'Bager' WHERE (`ID`='600022') AND (`Locale`='ruRU');
UPDATE `gossip_menu_option` SET `OptionText`='Oso Pardo Blindado (logro ID: 2076)' WHERE (`MenuID`='600022') AND (`OptionIndex`='2');
UPDATE `gossip_menu_option` SET `OptionText`='Oso Pardo Blindado (logro ID: 2076)' WHERE (`MenuID`='600022') AND (`OptionIndex`='1');
UPDATE `gossip_menu_option` SET `OptionText`='El paraíso perdido (questID: 39718)' WHERE (`MenuID`='600022') AND (`OptionIndex`='14');


UPDATE `creature_template_wdb` SET `Title`='Reparaciones' WHERE (`Entry`='600023');
UPDATE `creature_template_wdb_locale` SET `Locale`='esES', `Title`='Correcciones' WHERE (`ID`='600023') AND (`Locale`='ruRU');
UPDATE `creature_template_wdb_locale` SET `Name1`='O\'Shea' WHERE (`ID`='600023') AND (`Locale`='esES');
UPDATE `gossip_menu_option` SET `OptionText`='Información.' WHERE (`MenuID`='600023') AND (`OptionIndex`='4');
UPDATE `gossip_menu_option` SET `OptionText`='Retira tu Garrison. (!Uselo SOLAMENTE si su Garrison esta roto despues de cambiar Facción!)' WHERE (`MenuID`='600023') AND (`OptionIndex`='3');
UPDATE `trinity_string` SET `content_default`='Ingrese el ID de la misión:', `content_loc8`='Ingrese la ID de búsqueda:' WHERE (`entry`='600023');
