UPDATE `quest_template` SET `RewardItem1`='505051', `RewardAmount1`='1' WHERE `ID` IN (
'60011',
'60012',
'60013',
'60014',
'60015',
'60016',
'60017',
'60018',
'60019',
'60021',
'60022',
'60023',
'60024',
'60025',
'60026',
'60028',
'60029');

DELETE FROM `quest_template_locale` WHERE `ID` IN (
'60011',
'60012',
'60013',
'60014',
'60015',
'60016',
'60017',
'60018',
'60019',
'60021',
'60022',
'60023',
'60024',
'60025',
'60026',
'60028',
'60029');

INSERT INTO `quest_template_locale` (`ID`, `locale`, `LogTitle`, `LogDescription`, `QuestDescription`, `AreaDescription`, `PortraitGiverText`, `PortraitGiverName`, `PortraitTurnInText`, `PortraitTurnInName`, `QuestCompletionLog`, `VerifiedBuild`) VALUES 
('60011', 'esES', 'Diez de diez', 'Completa 10 misiones de mundo', 'Si quieres llevarte esta recompensa, completa 10 misiones de mundo', '', '', '', '', '', '', '26124'),
('60012', 'esES', 'A la batalla', 'Gana 3 campos de batalla.', '¿Estás listo para la batalla? Gana 3 campos de batalla al azar y regresa por tu recompensa.', '', '', '', '', '', '', '26124'),
('60013', 'esES', 'Solo vencerlos', 'Gana 5 arenas.', '¿Qué hay de algunas arenas? Gana 5 arenas clasificadas y vuelve a mí.', '', '', '', '', '', '', '26124'),
('60014', 'esES', 'Buscador de mazmorras', 'Termina 3 mazmorras heroicas con Buscador de mazmorras.', 'Termina 3 mazmorras heroicas con Buscador de mazmorras.', '', '', '', '', '', '', '26124'),
('60015', 'esES', 'Tiempo de Bandas', 'Mata a Ursoc en la incursión de Pesadilla Esmeralda.', 'Ve a la Pesadilla Esmeralda y mata a Ursoc', '', '', '', '', '', '', '26124'),
('60016', 'esES', 'Tiempo de Bandas', 'Mata a Tichondrius en la incursión de Nighthold.', 'Ve a la Nighthold y mata a Tichondrius.', '', '', '', '', '', '', '26124'),
('60017', 'esES', 'Tiempo de Bandas', 'Mata a Harjatan en la incursión de la Tumba de los Sargeras', 'Ve a la Tumba de las Sargeras y mata a Harjatan', '', '', '', '', '', '', '26124'),
('60018', 'esES', 'Tiempo de Bandas', 'Mata a Garothi Worldbreaker en Antorus, la incursión del trono en llamas.', 'Ve al Antorus, el trono en llamas y mata a Garothi Worldbreaker', '', '', '', '', '', '', '26124'),
('60019', 'esES', 'Oh llave', 'Completa mazmorra mítica con piedra angular.', 'Completa mazmorra mítica con piedra angular.', '', '', '', '', '', '', '26124'),
('60021', 'esES', 'Invasi\ón de la Legi\ón: Baldíos', 'Apoya a tu facción en la invasi\ón de la Legión en Crossroads, Baldíos del Norte.', '¡Dirígete a Crossroads en Baldíos del Norte y apoya a Horde!', '', '', '', '', '', '', '26124'),
('60022', 'esES', 'Invasi\ón de la Legión: Paramos de Poniente', 'Apoya a tu facción en la invasi\ón de la Legión en la colina del Centinela, Paramos de Poniente.', '¡Ve a la colina del Centinela en Paramos de Poniente y apoya a la Alianza!', '', '', '', '', '', '', '26124'),
('60023', 'esES', 'Batalla en Skyfire', 'Ataque al buque de guerra de la alianza.', 'Necesitas suspirar un documento sobre mi mesa cuando estés listo para viajar en el acorazado.', '', '', '', '', '', '', '26124'),
('60024', 'esES', 'Batalla en Skyfire', 'Defiende la alianza del acorazado.', 'Necesitas suspirar un documento sobre mi mesa cuando estés listo para viajar en el acorazado.', '', '', '', '', '', '', '26124'),
('60025', 'esES', 'La grieta', 'Explora una de las grietas que abrió Ennera.', 'Ennera visita Dalaran varias veces al día y abre algunas grietas. Ir a uno de ellos y explorarlo', '', '', '', '', '', '', '26124'),
('60026', 'esES', 'Apoyo en Grito de Guerra', 'Apoya a tu facción en Warsong Gulch.', 'Tu facción necesita apoyo en Warsong Gulch. Firme el documento sobre la mesa si está listo.', '', '', '', '', '', '', '26124'),
('60028', 'esES', 'Elevado', 'Encuentra y mata al dragón helado criado en Cementerio de Dragones.', 'Puedes encontrar este dragón en Cementerio de Dragones cerca del Templo Wyrmrest. Nuestros exploradores informarán cuando vean al dragón.', '', '', '', '', '', '', '26124'),
('60029', 'esES', 'Una Val\'kyr, dos Val\'kyr', 'Mata a Val\'kyr en Cuna de Invierno.', '¿Se puede vencer a Val\'kyr? ¿Qué pasa si no habrá uno? De todos modos, te daré una moneda de hielo si vas a Cuna de Invierno a Kel\'theril Lake y terminas con val\'kyrs.', '', '', '', '', '', '', '26124'),

('60011', 'esMX', 'Diez de diez', 'Completa 10 misiones de mundo', 'Si quieres llevarte esta recompensa, completa 10 misiones de mundo', '', '', '', '', '', '', '26124'),
('60012', 'esMX', '¡A la batalla!', 'Gana 3 campos de batalla.', '¿Estás listo para la batalla? Gana 3 campos de batalla al azar y regresa por tu recompensa.', '', '', '', '', '', '', '26124'),
('60013', 'esMX', 'Solo vencerlos', 'Gana 5 arenas.', '¿Qué hay de algunas arenas? Gana 5 arenas clasificadas y vuelve a mí.', '', '', '', '', '', '', '26124'),
('60014', 'esMX', 'Buscador de mazmorras', 'Termina 3 mazmorras heroicas con Buscador de mazmorras.', 'Termina 3 mazmorras heroicas con Buscador de mazmorras.', '', '', '', '', '', '', '26124'),
('60015', 'esMX', 'Tiempo de Bandas', 'Mata a Ursoc en la incursión de Pesadilla Esmeralda.', 'Ve a la Pesadilla Esmeralda y mata a Ursoc', '', '', '', '', '', '', '26124'),
('60016', 'esMX', 'Tiempo de Bandas', 'Mata a Tichondrius en la incursión de Nighthold.', 'Ve a la Nighthold y mata a Tichondrius.', '', '', '', '', '', '', '26124'),
('60017', 'esMX', 'Tiempo de Bandas', 'Mata a Harjatan en la incursión de la Tumba de los Sargeras', 'Ve a la Tumba de las Sargeras y mata a Harjatan', '', '', '', '', '', '', '26124'),
('60018', 'esMX', 'Tiempo de Bandas', 'Mata a Garothi Worldbreaker en Antorus, la incursión del trono en llamas.', 'Ve al Antorus, el trono en llamas y mata a Garothi Worldbreaker', '', '', '', '', '', '', '26124'),
('60019', 'esMX', 'Oh llave', 'Completa mazmorra mítica con piedra angular.', 'Completa mazmorra mítica con piedra angular.', '', '', '', '', '', '', '26124'),
('60021', 'esMX', 'Invasi\ón de la Legión: Baldíos', 'Apoya a tu facción en la invasi\ón de la Legión en Crossroads, Baldíos del Norte.', '¡Dirígete a Crossroads en Baldíos del Norte y apoya a Horde!', '', '', '', '', '', '', '26124'),
('60022', 'esMX', 'Invasi\ón de la Legión: Paramos de Poniente', 'Apoya a tu facción en la invasi\ón de la Legión en la colina del Centinela, Paramos de Poniente.', '¡Ve a la colina del Centinela en Paramos de Poniente y apoya a la Alianza!', '', '', '', '', '', '', '26124'),
('60023', 'esMX', 'Batalla en Skyfire', 'Ataque al buque de guerra de la alianza.', 'Necesitas suspirar un documento sobre mi mesa cuando estés listo para viajar en el acorazado.', '', '', '', '', '', '', '26124'),
('60024', 'esMX', 'Batalla en Skyfire', 'Defiende la alianza del acorazado.', 'Necesitas suspirar un documento sobre mi mesa cuando estés listo para viajar en el acorazado.', '', '', '', '', '', '', '26124'),
('60025', 'esMX', 'La grieta', 'Explora una de las grietas que abrió Ennera.', 'Ennera visita Dalaran varias veces al día y abre algunas grietas. Ir a uno de ellos y explorarlo', '', '', '', '', '', '', '26124'),
('60026', 'esMX', 'Apoyo en Grito de Guerra', 'Apoya a tu facción en Warsong Gulch.', 'Tu facción necesita apoyo en Warsong Gulch. Firme el documento sobre la mesa si está listo.', '', '', '', '', '', '', '26124'),
('60028', 'esMX', 'Elevado', 'Encuentra y mata al dragón helado criado en Cementerio de Dragones.', 'Puedes encontrar este dragón en Cementerio de Dragones cerca del Templo Wyrmrest. Nuestros exploradores informarán cuando vean al dragón.', '', '', '', '', '', '', '26124'),
('60029', 'esMX', 'Una Val\'kyr, dos Val\'kyr', 'Mata a Val\'kyr en Cuna de Invierno.', '¿Se puede vencer a Val\'kyr? ¿Qué pasa si no habrá uno? De todos modos, te daré una moneda de hielo si vas a Cuna de Invierno a Kel\'theril Lake y terminas con val\'kyrs.', '', '', '', '', '', '', '26124');

