/*
Incidencia 86 link http://10.96.2.9/bugtracker/view.php?id=86
*/
DELETE FROM `smart_scripts` WHERE `entryorguid`='18069' AND `id`='14';  
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES ('18069', '0', '14', '0', '6', '0', '100', '1', '0', '0', '0', '0', '15', '9977', '0', '0', '0', '0', '0', '16', '0', '0', '0', '0', '0', '0', '0', 'Mogor - On Death - Give Quest Credit');

/*
Incidencia 167 link http://10.96.2.9/bugtracker/view.php?id=167
*/
UPDATE `creature_loot_template` SET `ChanceOrQuestChance`='100' WHERE `entry`='33289';
UPDATE `creature_template` SET `faction`='35' WHERE `entry`='33303';

/*
Incidencia 170 
link http://10.96.2.9/bugtracker/view.php?id=170
*/
DELETE FROM `creature_template` WHERE `entry` = 33238;
INSERT INTO `creature_template` (`entry`, `gossip_menu_id`, `minlevel`, `maxlevel`, `SandboxScalingID`, `ScaleLevelMin`, `ScaleLevelMax`, `ScaleLevelDelta`, `ScaleLevelDuration`, `exp`, `faction`, `npcflag`, `npcflag2`, `speed_walk`, `speed_run`, `speed_fly`, `scale`, `mindmg`, `maxdmg`, `dmgschool`, `attackpower`, `dmg_multiplier`, `baseattacktime`, `rangeattacktime`, `unit_class`, `unit_flags`, `unit_flags2`, `unit_flags3`, `dynamicflags`, `trainer_type`, `trainer_spell`, `trainer_class`, `trainer_race`, `minrangedmg`, `maxrangedmg`, `rangedattackpower`, `lootid`, `pickpocketloot`, `skinloot`, `resistance1`, `resistance2`, `resistance3`, `resistance4`, `resistance5`, `resistance6`, `spell1`, `spell2`, `spell3`, `spell4`, `spell5`, `spell6`, `spell7`, `spell8`, `PetSpellDataId`, `VehicleId`, `mingold`, `maxgold`, `AIName`, `MovementType`, `InhabitType`, `HoverHeight`, `Mana_mod_extra`, `Armor_mod`, `RegenHealth`, `mechanic_immune_mask`, `flags_extra`, `ControllerID`, `WorldEffects`, `PassiveSpells`, `StateWorldEffectID`, `SpellStateVisualID`, `SpellStateAnimID`, `SpellStateAnimKitID`, `IgnoreLos`, `AffixState`, `MaxVisible`, `ScriptName`) VALUES ('33238', '10318', '90', '90', '0', '0', '0', '0', '0', '2', '2203', '67240065', '0', '1', '0.992063', '1.14286', '1', '1', '2', '0', '0', '1', '2000', '2000', '1', '0', '2048', '0', '0', '0', '0', '0', '0', '1', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', 'SmartAI', '0', '3', '1', '1', '1', '1', '0', '2', '0', '', '', '0', '0', '0', '0', '0', '0', '0', '');

DELETE FROM `creature_template_wdb` WHERE `Entry` = 33238;
INSERT INTO `creature_template_wdb` (`Entry`, `Name1`, `Name2`, `Name3`, `Name4`, `NameAlt1`, `NameAlt2`, `NameAlt3`, `NameAlt4`, `Title`, `TitleAlt`, `CursorName`, `TypeFlags`, `TypeFlags2`, `Type`, `Family`, `Classification`, `KillCredit1`, `KillCredit2`, `VignetteID`, `Displayid1`, `Displayid2`, `Displayid3`, `Displayid4`, `HpMulti`, `PowerMulti`, `Leader`, `QuestItem1`, `QuestItem2`, `QuestItem3`, `QuestItem4`, `QuestItem5`, `QuestItem6`, `QuestItem7`, `QuestItem8`, `QuestItem9`, `QuestItem10`, `MovementInfoID`, `RequiredExpansion`, `FlagQuest`, `VerifiedBuild`) VALUES ('33238', 'Argent Squire', '', '', '', '', '', '', '', '', '', 'wildpetcapturable', '8388608', '0', '12', '0', '0', '0', '0', '0', '28946', '0', '0', '0', '1', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '22566');

DELETE FROM `gossip_menu` WHERE `Entry` = 10318;
INSERT INTO `gossip_menu` (`Entry`, `TextID`, `FriendshipFactionID`) VALUES ('10318', '14324', '0');

DELETE FROM `gossip_menu_option` WHERE `MenuId` = 10318;
INSERT INTO `gossip_menu_option` (`MenuID`, `OptionIndex`, `OptionNPC`, `OptionText`, `OptionType`, `OptionNpcflag`, `OptionNpcflag2`, `ActionMenuID`, `ActionPoiID`, `BoxCoded`, `BoxMoney`, `BoxCurrency`, `BoxText`, `OptionBroadcastTextID`, `BoxBroadcastTextID`, `VerifiedBuild`) VALUES ('10318', '0', '6', 'Visit a bank', '9', '131072', '0', '0', '0', '0', '0', '0', NULL, '0', '0', '0');
INSERT INTO `gossip_menu_option` (`MenuID`, `OptionIndex`, `OptionNPC`, `OptionText`, `OptionType`, `OptionNpcflag`, `OptionNpcflag2`, `ActionMenuID`, `ActionPoiID`, `BoxCoded`, `BoxMoney`, `BoxCurrency`, `BoxText`, `OptionBroadcastTextID`, `BoxBroadcastTextID`, `VerifiedBuild`) VALUES ('10318', '1', '1', 'Visit a trader', '3', '128', '0', '0', '0', '0', '0', '0', NULL, '0', '0', '0');
INSERT INTO `gossip_menu_option` (`MenuID`, `OptionIndex`, `OptionNPC`, `OptionText`, `OptionType`, `OptionNpcflag`, `OptionNpcflag2`, `ActionMenuID`, `ActionPoiID`, `BoxCoded`, `BoxMoney`, `BoxCurrency`, `BoxText`, `OptionBroadcastTextID`, `BoxBroadcastTextID`, `VerifiedBuild`) VALUES ('10318', '2', '0', 'Visit a mailbox', '20', '67108864', '0', '0', '0', '0', '0', '0', NULL, '0', '0', '0');
INSERT INTO `gossip_menu_option` (`MenuID`, `OptionIndex`, `OptionNPC`, `OptionText`, `OptionType`, `OptionNpcflag`, `OptionNpcflag2`, `ActionMenuID`, `ActionPoiID`, `BoxCoded`, `BoxMoney`, `BoxCurrency`, `BoxText`, `OptionBroadcastTextID`, `BoxBroadcastTextID`, `VerifiedBuild`) VALUES ('10318', '3', '0', 'Darnassus Champion\'s Pennant', '1', '1', '0', '0', '0', '0', '0', '0', NULL, '33675', '0', '0');
INSERT INTO `gossip_menu_option` (`MenuID`, `OptionIndex`, `OptionNPC`, `OptionText`, `OptionType`, `OptionNpcflag`, `OptionNpcflag2`, `ActionMenuID`, `ActionPoiID`, `BoxCoded`, `BoxMoney`, `BoxCurrency`, `BoxText`, `OptionBroadcastTextID`, `BoxBroadcastTextID`, `VerifiedBuild`) VALUES ('10318', '4', '0', 'Exodar Champion\'s Pennant', '1', '1', '0', '0', '0', '0', '0', '0', NULL, '33676', '0', '0');
INSERT INTO `gossip_menu_option` (`MenuID`, `OptionIndex`, `OptionNPC`, `OptionText`, `OptionType`, `OptionNpcflag`, `OptionNpcflag2`, `ActionMenuID`, `ActionPoiID`, `BoxCoded`, `BoxMoney`, `BoxCurrency`, `BoxText`, `OptionBroadcastTextID`, `BoxBroadcastTextID`, `VerifiedBuild`) VALUES ('10318', '5', '0', 'Gnomeregan Champion\'s Pennant', '1', '1', '0', '0', '0', '0', '0', '0', NULL, '33678', '0', '0');
INSERT INTO `gossip_menu_option` (`MenuID`, `OptionIndex`, `OptionNPC`, `OptionText`, `OptionType`, `OptionNpcflag`, `OptionNpcflag2`, `ActionMenuID`, `ActionPoiID`, `BoxCoded`, `BoxMoney`, `BoxCurrency`, `BoxText`, `OptionBroadcastTextID`, `BoxBroadcastTextID`, `VerifiedBuild`) VALUES ('10318', '6', '0', 'Ironforge Champion\'s Pennant', '1', '1', '0', '0', '0', '0', '0', '0', NULL, '33679', '0', '0');
INSERT INTO `gossip_menu_option` (`MenuID`, `OptionIndex`, `OptionNPC`, `OptionText`, `OptionType`, `OptionNpcflag`, `OptionNpcflag2`, `ActionMenuID`, `ActionPoiID`, `BoxCoded`, `BoxMoney`, `BoxCurrency`, `BoxText`, `OptionBroadcastTextID`, `BoxBroadcastTextID`, `VerifiedBuild`) VALUES ('10318', '7', '0', 'Stormwind Champion\'s Pennant', '1', '1', '0', '0', '0', '0', '0', '0', NULL, '33401', '0', '0');

DELETE FROM `conditions` WHERE `SourceGroup` = 10318;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES ('15', '10318', '0', '0', '0', '1', '0', '67334', '0', '0', '1', '0', '', 'Oculta banco cuando se utiliza');
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES ('15', '10318', '0', '0', '1', '1', '1', '67368', '0', '0', '0', '0', '', 'Continuar usando banco');
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES ('15', '10318', '1', '0', '1', '1', '1', '67377', '0', '0', '0', '0', '', 'Continuar usando tienda');
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES ('15', '10318', '1', '0', '0', '1', '0', '67334', '0', '0', '1', '0', '', 'Oculta tienda cuando se utiliza');
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES ('15', '10318', '2', '0', '1', '1', '1', '67376', '0', '0', '0', '0', '', 'Continuar usando el correo');
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES ('15', '10318', '2', '0', '0', '1', '0', '67334', '0', '0', '1', '0', '', 'Oculta correo cuando se utiliza');

DELETE FROM `smart_scripts` WHERE `entryorguid` = 33238;
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES ('33238', '0', '0', '8', '62', '0', '100', '1', '10318', '0', '0', '0', '11', '67368', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', 'On Gossip Option 0 Selected');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES ('33238', '0', '1', '8', '62', '0', '100', '1', '10318', '1', '0', '0', '11', '67377', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', 'On Gossip Option 1 Selected ');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES ('33238', '0', '2', '8', '62', '0', '100', '1', '10318', '2', '0', '0', '11', '67376', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', 'On Gossip Option 2 Selected ');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES ('33238', '0', '3', '10', '62', '0', '100', '0', '10318', '3', '0', '0', '80', '3323800', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', 'On Gossip Option 3 Selected Acionlist');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES ('33238', '0', '4', '11', '62', '0', '100', '0', '10318', '4', '0', '0', '80', '3323801', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', 'On Gossip Option 4 Selected Acionlist');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES ('33238', '0', '5', '12', '62', '0', '100', '0', '10318', '5', '0', '0', '80', '3323802', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', 'On Gossip Option 5 Selected Acionlist');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES ('33238', '0', '6', '13', '62', '0', '100', '0', '10318', '6', '0', '0', '80', '3323803', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', 'On Gossip Option 6 Selected Acionlist');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES ('33238', '0', '7', '14', '62', '0', '100', '0', '10318', '7', '0', '0', '80', '3323804', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', 'On Gossip Option 7 Selected Acionlist');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES ('33238', '0', '8', '9', '61', '0', '100', '1', '0', '0', '0', '0', '75', '67334', '0', '0', '0', '0', '0', '7', '0', '0', '0', '0', '0', '0', '0', 'Add aura 67334 on player');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES ('33238', '0', '9', '0', '61', '0', '100', '1', '0', '0', '0', '0', '11', '67401', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', 'cast 67401 on self');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES ('33238', '0', '10', '15', '61', '0', '100', '0', '0', '0', '0', '0', '11', '63443', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', 'On select gossip cast 63443');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES ('33238', '0', '11', '15', '61', '0', '100', '0', '0', '0', '0', '0', '11', '63439', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', 'On select gossip cast 63439');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES ('33238', '0', '12', '15', '61', '0', '100', '0', '0', '0', '0', '0', '11', '63442', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', 'On select gossip cast 63442');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES ('33238', '0', '13', '15', '61', '0', '100', '0', '0', '0', '0', '0', '11', '63440', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', 'On select gossip cast 63440');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES ('33238', '0', '14', '15', '61', '0', '100', '0', '0', '0', '0', '0', '11', '62728', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', 'On select gossip cast 62728');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES ('33238', '0', '15', '0', '61', '0', '100', '0', '0', '0', '0', '0', '72', '0', '0', '0', '0', '0', '0', '7', '0', '0', '0', '0', '0', '0', '0', 'Close gossip');

DELETE FROM `smart_scripts` WHERE `entryorguid` = 3323800;
DELETE FROM `smart_scripts` WHERE `entryorguid` = 3323801;
DELETE FROM `smart_scripts` WHERE `entryorguid` = 3323802;
DELETE FROM `smart_scripts` WHERE `entryorguid` = 3323803;
DELETE FROM `smart_scripts` WHERE `entryorguid` = 3323804;

INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES ('3323800', '9', '1', '0', '0', '0', '100', '0', '0', '0', '0', '0', '28', '63439', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', 'Remover aura 63439');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES ('3323800', '9', '2', '0', '0', '0', '100', '0', '0', '0', '0', '0', '28', '63442', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', 'Remover aura 63442');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES ('3323800', '9', '3', '0', '0', '0', '100', '0', '0', '0', '0', '0', '28', '63440', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', 'Remover aura 63440');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES ('3323800', '9', '4', '0', '0', '0', '100', '0', '0', '0', '0', '0', '28', '62728', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', 'Remover aura 62728');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES ('3323801', '9', '1', '0', '0', '0', '100', '0', '0', '0', '0', '0', '28', '63443', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', 'Remover aura 63443');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES ('3323801', '9', '2', '0', '0', '0', '100', '0', '0', '0', '0', '0', '28', '63442', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', 'Remover aura 63442');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES ('3323801', '9', '3', '0', '0', '0', '100', '0', '0', '0', '0', '0', '28', '63440', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', 'Remover aura 63440');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES ('3323801', '9', '4', '0', '0', '0', '100', '0', '0', '0', '0', '0', '28', '62728', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', 'Remover aura 62728');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES ('3323802', '9', '1', '0', '0', '0', '100', '0', '0', '0', '0', '0', '28', '63443', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', 'Remover aura 63443');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES ('3323802', '9', '2', '0', '0', '0', '100', '0', '0', '0', '0', '0', '28', '63439', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', 'Remover aura 63439');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES ('3323802', '9', '3', '0', '0', '0', '100', '0', '0', '0', '0', '0', '28', '63440', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', 'Remover aura 63440');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES ('3323802', '9', '4', '0', '0', '0', '100', '0', '0', '0', '0', '0', '28', '62728', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', 'Remover aura 62728');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES ('3323803', '9', '1', '0', '0', '0', '100', '0', '0', '0', '0', '0', '28', '63443', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', 'Remover aura 63443');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES ('3323803', '9', '2', '0', '0', '0', '100', '0', '0', '0', '0', '0', '28', '63439', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', 'Remover aura 63439');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES ('3323803', '9', '3', '0', '0', '0', '100', '0', '0', '0', '0', '0', '28', '63442', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', 'Remover aura 63442');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES ('3323803', '9', '4', '0', '0', '0', '100', '0', '0', '0', '0', '0', '28', '62728', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', 'Remover aura 62728');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES ('3323804', '9', '1', '0', '0', '0', '100', '0', '0', '0', '0', '0', '28', '63443', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', 'Remover aura 63443');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES ('3323804', '9', '2', '0', '0', '0', '100', '0', '0', '0', '0', '0', '28', '63439', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', 'Remover aura 63439');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES ('3323804', '9', '3', '0', '0', '0', '100', '0', '0', '0', '0', '0', '28', '63442', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', 'Remover aura 63442');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES ('3323804', '9', '4', '0', '0', '0', '100', '0', '0', '0', '0', '0', '28', '63440', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', 'Remover aura 63440');

DELETE FROM `npc_vendor` WHERE `entry` = 33238;
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `money`, `type`, `PlayerConditionID`, `IgnoreFiltering`, `RandomPropertiesSeed`, `RandomPropertiesID`, `BonusListID`, `ItemModifiers`, `Context`, `VerifiedBuild`) VALUES ('33238', '1', '33443', '0', '0', '0', '0', '1', '0', '0', '0', '0', '', '', '0', '0');
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `money`, `type`, `PlayerConditionID`, `IgnoreFiltering`, `RandomPropertiesSeed`, `RandomPropertiesID`, `BonusListID`, `ItemModifiers`, `Context`, `VerifiedBuild`) VALUES ('33238', '2', '40036', '0', '0', '0', '0', '1', '0', '0', '0', '0', '', '', '0', '0');
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `money`, `type`, `PlayerConditionID`, `IgnoreFiltering`, `RandomPropertiesSeed`, `RandomPropertiesID`, `BonusListID`, `ItemModifiers`, `Context`, `VerifiedBuild`) VALUES ('33238', '3', '40035', '0', '0', '0', '0', '1', '0', '0', '0', '0', '', '', '0', '0');
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `money`, `type`, `PlayerConditionID`, `IgnoreFiltering`, `RandomPropertiesSeed`, `RandomPropertiesID`, `BonusListID`, `ItemModifiers`, `Context`, `VerifiedBuild`) VALUES ('33238', '4', '35954', '0', '0', '0', '0', '1', '0', '0', '0', '0', '', '', '0', '0');
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `money`, `type`, `PlayerConditionID`, `IgnoreFiltering`, `RandomPropertiesSeed`, `RandomPropertiesID`, `BonusListID`, `ItemModifiers`, `Context`, `VerifiedBuild`) VALUES ('33238', '5', '35953', '0', '0', '0', '0', '1', '0', '0', '0', '0', '', '', '0', '0');
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `money`, `type`, `PlayerConditionID`, `IgnoreFiltering`, `RandomPropertiesSeed`, `RandomPropertiesID`, `BonusListID`, `ItemModifiers`, `Context`, `VerifiedBuild`) VALUES ('33238', '6', '35952', '0', '0', '0', '0', '1', '0', '0', '0', '0', '', '', '0', '0');
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `money`, `type`, `PlayerConditionID`, `IgnoreFiltering`, `RandomPropertiesSeed`, `RandomPropertiesID`, `BonusListID`, `ItemModifiers`, `Context`, `VerifiedBuild`) VALUES ('33238', '7', '35950', '0', '0', '0', '0', '1', '0', '0', '0', '0', '', '', '0', '0');
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `money`, `type`, `PlayerConditionID`, `IgnoreFiltering`, `RandomPropertiesSeed`, `RandomPropertiesID`, `BonusListID`, `ItemModifiers`, `Context`, `VerifiedBuild`) VALUES ('33238', '8', '35949', '0', '0', '0', '0', '1', '0', '0', '0', '0', '', '', '0', '0');
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `money`, `type`, `PlayerConditionID`, `IgnoreFiltering`, `RandomPropertiesSeed`, `RandomPropertiesID`, `BonusListID`, `ItemModifiers`, `Context`, `VerifiedBuild`) VALUES ('33238', '9', '35948', '0', '0', '0', '0', '1', '0', '0', '0', '0', '', '', '0', '0');
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `money`, `type`, `PlayerConditionID`, `IgnoreFiltering`, `RandomPropertiesSeed`, `RandomPropertiesID`, `BonusListID`, `ItemModifiers`, `Context`, `VerifiedBuild`) VALUES ('33238', '10', '35947', '0', '0', '0', '0', '1', '0', '0', '0', '0', '', '', '0', '0');
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `money`, `type`, `PlayerConditionID`, `IgnoreFiltering`, `RandomPropertiesSeed`, `RandomPropertiesID`, `BonusListID`, `ItemModifiers`, `Context`, `VerifiedBuild`) VALUES ('33238', '11', '33454', '0', '0', '0', '0', '1', '0', '0', '0', '0', '', '', '0', '0');
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `money`, `type`, `PlayerConditionID`, `IgnoreFiltering`, `RandomPropertiesSeed`, `RandomPropertiesID`, `BonusListID`, `ItemModifiers`, `Context`, `VerifiedBuild`) VALUES ('33238', '12', '33452', '0', '0', '0', '0', '1', '0', '0', '0', '0', '', '', '0', '0');
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `money`, `type`, `PlayerConditionID`, `IgnoreFiltering`, `RandomPropertiesSeed`, `RandomPropertiesID`, `BonusListID`, `ItemModifiers`, `Context`, `VerifiedBuild`) VALUES ('33238', '13', '33449', '0', '0', '0', '0', '1', '0', '0', '0', '0', '', '', '0', '0');
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `money`, `type`, `PlayerConditionID`, `IgnoreFiltering`, `RandomPropertiesSeed`, `RandomPropertiesID`, `BonusListID`, `ItemModifiers`, `Context`, `VerifiedBuild`) VALUES ('33238', '14', '33445', '0', '0', '0', '0', '1', '0', '0', '0', '0', '', '', '0', '0');
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `money`, `type`, `PlayerConditionID`, `IgnoreFiltering`, `RandomPropertiesSeed`, `RandomPropertiesID`, `BonusListID`, `ItemModifiers`, `Context`, `VerifiedBuild`) VALUES ('33238', '15', '33444', '0', '0', '0', '0', '1', '0', '0', '0', '0', '', '', '0', '0');
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `money`, `type`, `PlayerConditionID`, `IgnoreFiltering`, `RandomPropertiesSeed`, `RandomPropertiesID`, `BonusListID`, `ItemModifiers`, `Context`, `VerifiedBuild`) VALUES ('33238', '16', '40042', '0', '0', '0', '0', '1', '0', '0', '0', '0', '', '', '0', '0');

DELETE FROM `creature_template` WHERE `entry` = 33239;
INSERT INTO `creature_template` (`entry`, `gossip_menu_id`, `minlevel`, `maxlevel`, `SandboxScalingID`, `ScaleLevelMin`, `ScaleLevelMax`, `ScaleLevelDelta`, `ScaleLevelDuration`, `exp`, `faction`, `npcflag`, `npcflag2`, `speed_walk`, `speed_run`, `speed_fly`, `scale`, `mindmg`, `maxdmg`, `dmgschool`, `attackpower`, `dmg_multiplier`, `baseattacktime`, `rangeattacktime`, `unit_class`, `unit_flags`, `unit_flags2`, `unit_flags3`, `dynamicflags`, `trainer_type`, `trainer_spell`, `trainer_class`, `trainer_race`, `minrangedmg`, `maxrangedmg`, `rangedattackpower`, `lootid`, `pickpocketloot`, `skinloot`, `resistance1`, `resistance2`, `resistance3`, `resistance4`, `resistance5`, `resistance6`, `spell1`, `spell2`, `spell3`, `spell4`, `spell5`, `spell6`, `spell7`, `spell8`, `PetSpellDataId`, `VehicleId`, `mingold`, `maxgold`, `AIName`, `MovementType`, `InhabitType`, `HoverHeight`, `Mana_mod_extra`, `Armor_mod`, `RegenHealth`, `mechanic_immune_mask`, `flags_extra`, `ControllerID`, `WorldEffects`, `PassiveSpells`, `StateWorldEffectID`, `SpellStateVisualID`, `SpellStateAnimID`, `SpellStateAnimKitID`, `IgnoreLos`, `AffixState`, `MaxVisible`, `ScriptName`) VALUES ('33239', '10358', '90', '90', '0', '0', '0', '0', '0', '2', '2204', '67240065', '0', '1', '0.992063', '1.14286', '1', '1', '2', '0', '0', '1', '2000', '2000', '1', '0', '2048', '0', '0', '0', '0', '0', '0', '1', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', 'SmartAI', '0', '3', '1', '1', '1', '1', '0', '2', '0', '', '', '0', '0', '0', '0', '0', '0', '0', '');

DELETE FROM `creature_template_wdb` WHERE `Entry` = 33239;
INSERT INTO `creature_template_wdb` (`Entry`, `Name1`, `Name2`, `Name3`, `Name4`, `NameAlt1`, `NameAlt2`, `NameAlt3`, `NameAlt4`, `Title`, `TitleAlt`, `CursorName`, `TypeFlags`, `TypeFlags2`, `Type`, `Family`, `Classification`, `KillCredit1`, `KillCredit2`, `VignetteID`, `Displayid1`, `Displayid2`, `Displayid3`, `Displayid4`, `HpMulti`, `PowerMulti`, `Leader`, `QuestItem1`, `QuestItem2`, `QuestItem3`, `QuestItem4`, `QuestItem5`, `QuestItem6`, `QuestItem7`, `QuestItem8`, `QuestItem9`, `QuestItem10`, `MovementInfoID`, `RequiredExpansion`, `FlagQuest`, `VerifiedBuild`) VALUES ('33239', 'Argent Gruntling', '', '', '', '', '', '', '', '', '', 'wildpetcapturable', '8388608', '0', '12', '0', '0', '0', '0', '0', '28948', '0', '0', '0', '1', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '22566');

DELETE FROM `gossip_menu` WHERE `Entry` = 10358;
INSERT INTO `gossip_menu` (`Entry`, `TextID`, `FriendshipFactionID`) VALUES ('10358', '14372', '0');

DELETE FROM `gossip_menu_option` WHERE `MenuId` = 10358;
INSERT INTO `gossip_menu_option` (`MenuID`, `OptionIndex`, `OptionNPC`, `OptionText`, `OptionType`, `OptionNpcflag`, `OptionNpcflag2`, `ActionMenuID`, `ActionPoiID`, `BoxCoded`, `BoxMoney`, `BoxCurrency`, `BoxText`, `OptionBroadcastTextID`, `BoxBroadcastTextID`, `VerifiedBuild`) VALUES ('10358', '0', '6', 'Visit a bank.', '9', '131072', '0', '0', '0', '0', '0', '0', NULL, '35513', '0', '0');
INSERT INTO `gossip_menu_option` (`MenuID`, `OptionIndex`, `OptionNPC`, `OptionText`, `OptionType`, `OptionNpcflag`, `OptionNpcflag2`, `ActionMenuID`, `ActionPoiID`, `BoxCoded`, `BoxMoney`, `BoxCurrency`, `BoxText`, `OptionBroadcastTextID`, `BoxBroadcastTextID`, `VerifiedBuild`) VALUES ('10358', '1', '1', 'Visit a trader.', '3', '128', '0', '0', '0', '0', '0', '0', NULL, '35515', '0', '0');
INSERT INTO `gossip_menu_option` (`MenuID`, `OptionIndex`, `OptionNPC`, `OptionText`, `OptionType`, `OptionNpcflag`, `OptionNpcflag2`, `ActionMenuID`, `ActionPoiID`, `BoxCoded`, `BoxMoney`, `BoxCurrency`, `BoxText`, `OptionBroadcastTextID`, `BoxBroadcastTextID`, `VerifiedBuild`) VALUES ('10358', '2', '18', 'Visit a mailbox.', '20', '67108864', '0', '0', '0', '0', '0', '0', NULL, '35534', '0', '0');
INSERT INTO `gossip_menu_option` (`MenuID`, `OptionIndex`, `OptionNPC`, `OptionText`, `OptionType`, `OptionNpcflag`, `OptionNpcflag2`, `ActionMenuID`, `ActionPoiID`, `BoxCoded`, `BoxMoney`, `BoxCurrency`, `BoxText`, `OptionBroadcastTextID`, `BoxBroadcastTextID`, `VerifiedBuild`) VALUES ('10358', '3', '0', 'Darkspear Champion\'s Pennant', '1', '1', '0', '0', '0', '0', '0', '0', NULL, '33681', '0', '0');
INSERT INTO `gossip_menu_option` (`MenuID`, `OptionIndex`, `OptionNPC`, `OptionText`, `OptionType`, `OptionNpcflag`, `OptionNpcflag2`, `ActionMenuID`, `ActionPoiID`, `BoxCoded`, `BoxMoney`, `BoxCurrency`, `BoxText`, `OptionBroadcastTextID`, `BoxBroadcastTextID`, `VerifiedBuild`) VALUES ('10358', '4', '0', 'Forsaken Champion\'s Pennant', '1', '1', '0', '0', '0', '0', '0', '0', NULL, '33682', '0', '0');
INSERT INTO `gossip_menu_option` (`MenuID`, `OptionIndex`, `OptionNPC`, `OptionText`, `OptionType`, `OptionNpcflag`, `OptionNpcflag2`, `ActionMenuID`, `ActionPoiID`, `BoxCoded`, `BoxMoney`, `BoxCurrency`, `BoxText`, `OptionBroadcastTextID`, `BoxBroadcastTextID`, `VerifiedBuild`) VALUES ('10358', '5', '0', 'Orgrimmar Champion\'s Pennant', '1', '1', '0', '0', '0', '0', '0', '0', NULL, '33683', '0', '0');
INSERT INTO `gossip_menu_option` (`MenuID`, `OptionIndex`, `OptionNPC`, `OptionText`, `OptionType`, `OptionNpcflag`, `OptionNpcflag2`, `ActionMenuID`, `ActionPoiID`, `BoxCoded`, `BoxMoney`, `BoxCurrency`, `BoxText`, `OptionBroadcastTextID`, `BoxBroadcastTextID`, `VerifiedBuild`) VALUES ('10358', '6', '0', 'Silvermoon Champion\'s Pennant', '1', '1', '0', '0', '0', '0', '0', '0', NULL, '33685', '0', '0');
INSERT INTO `gossip_menu_option` (`MenuID`, `OptionIndex`, `OptionNPC`, `OptionText`, `OptionType`, `OptionNpcflag`, `OptionNpcflag2`, `ActionMenuID`, `ActionPoiID`, `BoxCoded`, `BoxMoney`, `BoxCurrency`, `BoxText`, `OptionBroadcastTextID`, `BoxBroadcastTextID`, `VerifiedBuild`) VALUES ('10358', '7', '0', 'Thunder Bluff Champion\'s Pennant', '1', '1', '0', '0', '0', '0', '0', '0', NULL, '33686', '0', '0');

DELETE FROM `conditions` WHERE `SourceGroup` = 10358;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES ('15', '10358', '0', '0', '0', '1', '0', '67334', '0', '0', '1', '0', '', 'Oculta banco cuando se utiliza');
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES ('15', '10358', '0', '0', '1', '1', '1', '68849', '0', '0', '0', '0', '', 'Continuar usando banco');
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES ('15', '10358', '1', '0', '1', '1', '1', '68851', '0', '0', '0', '0', '', 'Continuar usando tienda');
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES ('15', '10358', '1', '0', '0', '1', '0', '67334', '0', '0', '1', '0', '', 'Oculta tienda cuando se utiliza');
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES ('15', '10358', '2', '0', '1', '1', '1', '68850', '0', '0', '0', '0', '', 'Continuar usando el correo');
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES ('15', '10358', '2', '0', '0', '1', '0', '67334', '0', '0', '1', '0', '', 'Oculta correo cuando se utiliza');

DELETE FROM `smart_scripts` WHERE `entryorguid` = 33239;
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES ('33239', '0', '0', '8', '62', '0', '100', '1', '10358', '0', '0', '0', '11', '68849', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', 'On Gossip Option 0 Selected');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES ('33239', '0', '1', '8', '62', '0', '100', '1', '10358', '1', '0', '0', '11', '68851', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', 'On Gossip Option 1 Selected ');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES ('33239', '0', '2', '8', '62', '0', '100', '1', '10358', '2', '0', '0', '11', '68850', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', 'On Gossip Option 2 Selected ');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES ('33239', '0', '3', '10', '62', '0', '100', '0', '10358', '3', '0', '0', '80', '3323900', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', 'On Gossip Option 3 Selected Acionlist');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES ('33239', '0', '4', '11', '62', '0', '100', '0', '10358', '4', '0', '0', '80', '3323901', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', 'On Gossip Option 4 Selected Acionlist');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES ('33239', '0', '5', '12', '62', '0', '100', '0', '10358', '5', '0', '0', '80', '3323902', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', 'On Gossip Option 5 Selected Acionlist');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES ('33239', '0', '6', '13', '62', '0', '100', '0', '10358', '6', '0', '0', '80', '3323903', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', 'On Gossip Option 6 Selected Acionlist');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES ('33239', '0', '7', '14', '62', '0', '100', '0', '10358', '7', '0', '0', '80', '3323904', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', 'On Gossip Option 7 Selected Acionlist');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES ('33239', '0', '8', '9', '61', '0', '100', '1', '0', '0', '0', '0', '75', '67334', '0', '0', '0', '0', '0', '7', '0', '0', '0', '0', '0', '0', '0', 'Add aura 67334 on player');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES ('33239', '0', '9', '0', '61', '0', '100', '1', '0', '0', '0', '0', '11', '68852', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', 'cast 68852 on self');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES ('33239', '0', '10', '15', '61', '0', '100', '0', '0', '0', '0', '0', '11', '63399', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', 'On select gossip cast 63399');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES ('33239', '0', '11', '15', '61', '0', '100', '0', '0', '0', '0', '0', '11', '63430', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', 'On select gossip cast 63430');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES ('33239', '0', '12', '15', '61', '0', '100', '0', '0', '0', '0', '0', '11', '63433', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', 'On select gossip cast 63433');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES ('33239', '0', '13', '15', '61', '0', '100', '0', '0', '0', '0', '0', '11', '63403', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', 'On select gossip cast 63403');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES ('33239', '0', '14', '15', '61', '0', '100', '0', '0', '0', '0', '0', '11', '63436', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', 'On select gossip cast 63436');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES ('33239', '0', '15', '0', '61', '0', '100', '0', '0', '0', '0', '0', '72', '0', '0', '0', '0', '0', '0', '7', '0', '0', '0', '0', '0', '0', '0', 'Close gossip');

DELETE FROM `smart_scripts` WHERE `entryorguid` = 3323900;
DELETE FROM `smart_scripts` WHERE `entryorguid` = 3323901;
DELETE FROM `smart_scripts` WHERE `entryorguid` = 3323902;
DELETE FROM `smart_scripts` WHERE `entryorguid` = 3323903;
DELETE FROM `smart_scripts` WHERE `entryorguid` = 3323904;
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES ('3323900', '9', '1', '0', '0', '0', '100', '0', '0', '0', '0', '0', '28', '63430', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', 'Remover aura 63430');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES ('3323900', '9', '2', '0', '0', '0', '100', '0', '0', '0', '0', '0', '28', '63433', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', 'Remover aura 63433');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES ('3323900', '9', '3', '0', '0', '0', '100', '0', '0', '0', '0', '0', '28', '63403', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', 'Remover aura 63403');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES ('3323900', '9', '4', '0', '0', '0', '100', '0', '0', '0', '0', '0', '28', '63436', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', 'Remover aura 63436');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES ('3323901', '9', '1', '0', '0', '0', '100', '0', '0', '0', '0', '0', '28', '63399', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', 'Remover aura 63399');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES ('3323901', '9', '2', '0', '0', '0', '100', '0', '0', '0', '0', '0', '28', '63433', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', 'Remover aura 63433');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES ('3323901', '9', '3', '0', '0', '0', '100', '0', '0', '0', '0', '0', '28', '63403', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', 'Remover aura 63403');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES ('3323901', '9', '4', '0', '0', '0', '100', '0', '0', '0', '0', '0', '28', '63436', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', 'Remover aura 63436');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES ('3323902', '9', '1', '0', '0', '0', '100', '0', '0', '0', '0', '0', '28', '63399', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', 'Remover aura 63399');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES ('3323902', '9', '2', '0', '0', '0', '100', '0', '0', '0', '0', '0', '28', '63430', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', 'Remover aura 63430');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES ('3323902', '9', '3', '0', '0', '0', '100', '0', '0', '0', '0', '0', '28', '63403', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', 'Remover aura 63403');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES ('3323902', '9', '4', '0', '0', '0', '100', '0', '0', '0', '0', '0', '28', '63436', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', 'Remover aura 63436');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES ('3323903', '9', '1', '0', '0', '0', '100', '0', '0', '0', '0', '0', '28', '63399', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', 'Remover aura 63399');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES ('3323903', '9', '2', '0', '0', '0', '100', '0', '0', '0', '0', '0', '28', '63430', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', 'Remover aura 63430');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES ('3323903', '9', '3', '0', '0', '0', '100', '0', '0', '0', '0', '0', '28', '63433', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', 'Remover aura 63433');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES ('3323903', '9', '4', '0', '0', '0', '100', '0', '0', '0', '0', '0', '28', '63436', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', 'Remover aura 63436');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES ('3323904', '9', '1', '0', '0', '0', '100', '0', '0', '0', '0', '0', '28', '63399', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', 'Remover aura 63399');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES ('3323904', '9', '2', '0', '0', '0', '100', '0', '0', '0', '0', '0', '28', '63430', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', 'Remover aura 63430');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES ('3323904', '9', '3', '0', '0', '0', '100', '0', '0', '0', '0', '0', '28', '63433', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', 'Remover aura 63433');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES ('3323904', '9', '4', '0', '0', '0', '100', '0', '0', '0', '0', '0', '28', '63403', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', 'Remover aura 63403');

DELETE FROM `npc_vendor` WHERE `entry` = 33239;
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `money`, `type`, `PlayerConditionID`, `IgnoreFiltering`, `RandomPropertiesSeed`, `RandomPropertiesID`, `BonusListID`, `ItemModifiers`, `Context`, `VerifiedBuild`) VALUES ('33239', '1', '33443', '0', '0', '0', '0', '1', '0', '0', '0', '0', '', '', '0', '0');
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `money`, `type`, `PlayerConditionID`, `IgnoreFiltering`, `RandomPropertiesSeed`, `RandomPropertiesID`, `BonusListID`, `ItemModifiers`, `Context`, `VerifiedBuild`) VALUES ('33239', '2', '40036', '0', '0', '0', '0', '1', '0', '0', '0', '0', '', '', '0', '0');
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `money`, `type`, `PlayerConditionID`, `IgnoreFiltering`, `RandomPropertiesSeed`, `RandomPropertiesID`, `BonusListID`, `ItemModifiers`, `Context`, `VerifiedBuild`) VALUES ('33239', '3', '40035', '0', '0', '0', '0', '1', '0', '0', '0', '0', '', '', '0', '0');
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `money`, `type`, `PlayerConditionID`, `IgnoreFiltering`, `RandomPropertiesSeed`, `RandomPropertiesID`, `BonusListID`, `ItemModifiers`, `Context`, `VerifiedBuild`) VALUES ('33239', '4', '35954', '0', '0', '0', '0', '1', '0', '0', '0', '0', '', '', '0', '0');
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `money`, `type`, `PlayerConditionID`, `IgnoreFiltering`, `RandomPropertiesSeed`, `RandomPropertiesID`, `BonusListID`, `ItemModifiers`, `Context`, `VerifiedBuild`) VALUES ('33239', '5', '35953', '0', '0', '0', '0', '1', '0', '0', '0', '0', '', '', '0', '0');
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `money`, `type`, `PlayerConditionID`, `IgnoreFiltering`, `RandomPropertiesSeed`, `RandomPropertiesID`, `BonusListID`, `ItemModifiers`, `Context`, `VerifiedBuild`) VALUES ('33239', '6', '35952', '0', '0', '0', '0', '1', '0', '0', '0', '0', '', '', '0', '0');
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `money`, `type`, `PlayerConditionID`, `IgnoreFiltering`, `RandomPropertiesSeed`, `RandomPropertiesID`, `BonusListID`, `ItemModifiers`, `Context`, `VerifiedBuild`) VALUES ('33239', '7', '35950', '0', '0', '0', '0', '1', '0', '0', '0', '0', '', '', '0', '0');
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `money`, `type`, `PlayerConditionID`, `IgnoreFiltering`, `RandomPropertiesSeed`, `RandomPropertiesID`, `BonusListID`, `ItemModifiers`, `Context`, `VerifiedBuild`) VALUES ('33239', '8', '35949', '0', '0', '0', '0', '1', '0', '0', '0', '0', '', '', '0', '0');
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `money`, `type`, `PlayerConditionID`, `IgnoreFiltering`, `RandomPropertiesSeed`, `RandomPropertiesID`, `BonusListID`, `ItemModifiers`, `Context`, `VerifiedBuild`) VALUES ('33239', '9', '35948', '0', '0', '0', '0', '1', '0', '0', '0', '0', '', '', '0', '0');
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `money`, `type`, `PlayerConditionID`, `IgnoreFiltering`, `RandomPropertiesSeed`, `RandomPropertiesID`, `BonusListID`, `ItemModifiers`, `Context`, `VerifiedBuild`) VALUES ('33239', '10', '35947', '0', '0', '0', '0', '1', '0', '0', '0', '0', '', '', '0', '0');
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `money`, `type`, `PlayerConditionID`, `IgnoreFiltering`, `RandomPropertiesSeed`, `RandomPropertiesID`, `BonusListID`, `ItemModifiers`, `Context`, `VerifiedBuild`) VALUES ('33239', '11', '33454', '0', '0', '0', '0', '1', '0', '0', '0', '0', '', '', '0', '0');
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `money`, `type`, `PlayerConditionID`, `IgnoreFiltering`, `RandomPropertiesSeed`, `RandomPropertiesID`, `BonusListID`, `ItemModifiers`, `Context`, `VerifiedBuild`) VALUES ('33239', '12', '33452', '0', '0', '0', '0', '1', '0', '0', '0', '0', '', '', '0', '0');
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `money`, `type`, `PlayerConditionID`, `IgnoreFiltering`, `RandomPropertiesSeed`, `RandomPropertiesID`, `BonusListID`, `ItemModifiers`, `Context`, `VerifiedBuild`) VALUES ('33239', '13', '33449', '0', '0', '0', '0', '1', '0', '0', '0', '0', '', '', '0', '0');
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `money`, `type`, `PlayerConditionID`, `IgnoreFiltering`, `RandomPropertiesSeed`, `RandomPropertiesID`, `BonusListID`, `ItemModifiers`, `Context`, `VerifiedBuild`) VALUES ('33239', '14', '33445', '0', '0', '0', '0', '1', '0', '0', '0', '0', '', '', '0', '0');
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `money`, `type`, `PlayerConditionID`, `IgnoreFiltering`, `RandomPropertiesSeed`, `RandomPropertiesID`, `BonusListID`, `ItemModifiers`, `Context`, `VerifiedBuild`) VALUES ('33239', '15', '33444', '0', '0', '0', '0', '1', '0', '0', '0', '0', '', '', '0', '0');
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `money`, `type`, `PlayerConditionID`, `IgnoreFiltering`, `RandomPropertiesSeed`, `RandomPropertiesID`, `BonusListID`, `ItemModifiers`, `Context`, `VerifiedBuild`) VALUES ('33239', '16', '40042', '0', '0', '0', '0', '1', '0', '0', '0', '0', '', '', '0', '0');

/*
From Ashamane:
Incidencia 0000171: Profecion de Alquimia : Carta de la fortuna Misteriosa 
link  http://10.96.2.9/bugtracker/view.php?id=171
*/

DELETE FROM `spell_loot_template` WHERE `Entry`='60838';
DELETE FROM `item_loot_template` WHERE `Entry`='60838';
DELETE FROM `spell_loot_template` WHERE `Entry`='84193';
INSERT INTO `spell_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`) VALUES ('84193', '60840', '0.5', '1', '1', '1', '1');
INSERT INTO `spell_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`) VALUES ('84193', '60841', '1', '1', '1', '1', '1');
INSERT INTO `spell_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`) VALUES ('84193', '60842', '1', '1', '1', '1', '1');
INSERT INTO `spell_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`) VALUES ('84193', '60843', '1', '1', '1', '1', '1');
INSERT INTO `spell_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`) VALUES ('84193', '60844', '0.5', '1', '1', '1', '1');
INSERT INTO `spell_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`) VALUES ('84193', '60845', '1', '1', '1', '1', '1');
INSERT INTO `spell_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`) VALUES ('84193', '62246', '2', '1', '1', '1', '1');
INSERT INTO `spell_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`) VALUES ('84193', '62247', '2', '1', '1', '1', '1');
INSERT INTO `spell_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`) VALUES ('84193', '62552', '2', '1', '1', '1', '1');
INSERT INTO `spell_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`) VALUES ('84193', '62553', '2', '1', '1', '1', '1');
INSERT INTO `spell_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`) VALUES ('84193', '62554', '2', '1', '1', '1', '1');
INSERT INTO `spell_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`) VALUES ('84193', '62555', '2', '1', '1', '1', '1');
INSERT INTO `spell_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`) VALUES ('84193', '62556', '2', '1', '1', '1', '1');
INSERT INTO `spell_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`) VALUES ('84193', '62557', '2', '1', '1', '1', '1');
INSERT INTO `spell_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`) VALUES ('84193', '62558', '2', '1', '1', '1', '1');
INSERT INTO `spell_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`) VALUES ('84193', '62559', '2', '1', '1', '1', '1');
INSERT INTO `spell_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`) VALUES ('84193', '62560', '2', '1', '1', '1', '1');
INSERT INTO `spell_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`) VALUES ('84193', '62561', '2', '1', '1', '1', '1');
INSERT INTO `spell_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`) VALUES ('84193', '62562', '2', '1', '1', '1', '1');
INSERT INTO `spell_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`) VALUES ('84193', '62563', '2', '1', '1', '1', '1');
INSERT INTO `spell_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`) VALUES ('84193', '62564', '2', '1', '1', '1', '1');
INSERT INTO `spell_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`) VALUES ('84193', '62565', '2', '1', '1', '1', '1');
INSERT INTO `spell_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`) VALUES ('84193', '62566', '2', '1', '1', '1', '1');
INSERT INTO `spell_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`) VALUES ('84193', '62567', '2', '1', '1', '1', '1');
INSERT INTO `spell_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`) VALUES ('84193', '62568', '2', '1', '1', '1', '1');
INSERT INTO `spell_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`) VALUES ('84193', '62569', '2', '1', '1', '1', '1');
INSERT INTO `spell_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`) VALUES ('84193', '62570', '2', '1', '1', '1', '1');
INSERT INTO `spell_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`) VALUES ('84193', '62571', '2', '1', '1', '1', '1');
INSERT INTO `spell_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`) VALUES ('84193', '62572', '2', '1', '1', '1', '1');
INSERT INTO `spell_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`) VALUES ('84193', '62573', '2', '1', '1', '1', '1');
INSERT INTO `spell_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`) VALUES ('84193', '62574', '2', '1', '1', '1', '1');
INSERT INTO `spell_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`) VALUES ('84193', '62575', '2', '1', '1', '1', '1');
INSERT INTO `spell_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`) VALUES ('84193', '62576', '2', '1', '1', '1', '1');
INSERT INTO `spell_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`) VALUES ('84193', '62577', '2', '1', '1', '1', '1');
INSERT INTO `spell_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`) VALUES ('84193', '62578', '2', '1', '1', '1', '1');
INSERT INTO `spell_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`) VALUES ('84193', '62579', '2', '1', '1', '1', '1');
INSERT INTO `spell_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`) VALUES ('84193', '62580', '2', '1', '1', '1', '1');
INSERT INTO `spell_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`) VALUES ('84193', '62581', '2', '1', '1', '1', '1');
INSERT INTO `spell_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`) VALUES ('84193', '62582', '2', '1', '1', '1', '1');
INSERT INTO `spell_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`) VALUES ('84193', '62583', '2', '1', '1', '1', '1');
INSERT INTO `spell_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`) VALUES ('84193', '62584', '2', '1', '1', '1', '1');
INSERT INTO `spell_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`) VALUES ('84193', '62585', '2', '1', '1', '1', '1');
INSERT INTO `spell_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`) VALUES ('84193', '62586', '2', '1', '1', '1', '1');
INSERT INTO `spell_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`) VALUES ('84193', '62587', '2', '1', '1', '1', '1');
INSERT INTO `spell_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`) VALUES ('84193', '62588', '2', '1', '1', '1', '1');
INSERT INTO `spell_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`) VALUES ('84193', '62589', '2', '1', '1', '1', '1');
INSERT INTO `spell_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`) VALUES ('84193', '62590', '2', '1', '1', '1', '1');
INSERT INTO `spell_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`) VALUES ('84193', '62591', '2', '1', '1', '1', '1');
INSERT INTO `spell_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`) VALUES ('84193', '62598', '1.5', '1', '1', '1', '1');
INSERT INTO `spell_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`) VALUES ('84193', '62599', '1', '1', '1', '1', '1');
INSERT INTO `spell_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`) VALUES ('84193', '62600', '1', '1', '1', '1', '1');
INSERT INTO `spell_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`) VALUES ('84193', '62601', '1', '1', '1', '1', '1');
INSERT INTO `spell_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`) VALUES ('84193', '62602', '1', '1', '1', '1', '1');
INSERT INTO `spell_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`) VALUES ('84193', '62603', '1', '1', '1', '1', '1');
INSERT INTO `spell_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`) VALUES ('84193', '62604', '1', '1', '1', '1', '1');
INSERT INTO `spell_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`) VALUES ('84193', '62605', '1', '1', '1', '1', '1');
INSERT INTO `spell_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `lootmode`, `groupid`, `mincountOrRef`, `maxcount`) VALUES ('84193', '62606', '1', '1', '1', '1', '1');




/*
Incidencia 	0000166: Más de la isla Interporal
Link http://10.96.2.9/bugtracker/view.php?id=166
A new script was implemented see comic
*/
DELETE FROM `creature_template` WHERE `entry`='71864';  
INSERT INTO `creature_template` (`entry`, `gossip_menu_id`, `minlevel`, `maxlevel`, `SandboxScalingID`, `ScaleLevelMin`, `ScaleLevelMax`, `ScaleLevelDelta`, `ScaleLevelDuration`, `exp`, `faction`, `npcflag`, `npcflag2`, `speed_walk`, `speed_run`, `speed_fly`, `scale`, `mindmg`, `maxdmg`, `dmgschool`, `attackpower`, `dmg_multiplier`, `baseattacktime`, `rangeattacktime`, `unit_class`, `unit_flags`, `unit_flags2`, `unit_flags3`, `dynamicflags`, `trainer_type`, `trainer_spell`, `trainer_class`, `trainer_race`, `minrangedmg`, `maxrangedmg`, `rangedattackpower`, `lootid`, `pickpocketloot`, `skinloot`, `resistance1`, `resistance2`, `resistance3`, `resistance4`, `resistance5`, `resistance6`, `spell1`, `spell2`, `spell3`, `spell4`, `spell5`, `spell6`, `spell7`, `spell8`, `PetSpellDataId`, `VehicleId`, `mingold`, `maxgold`, `AIName`, `MovementType`, `InhabitType`, `HoverHeight`, `Mana_mod_extra`, `Armor_mod`, `RegenHealth`, `mechanic_immune_mask`, `flags_extra`, `ControllerID`, `WorldEffects`, `PassiveSpells`, `StateWorldEffectID`, `SpellStateVisualID`, `SpellStateAnimID`, `SpellStateAnimKitID`, `IgnoreLos`, `AffixState`, `MaxVisible`, `ScriptName`) VALUES ('71864', '0', '90', '90', '0', '0', '0', '0', '0', '4', '14', '0', '0', '1', '1.14286', '1.14286', '1', '1268', '1752', '0', '0', '1.5', '2000', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '71864', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', 'SmartAI', '0', '3', '1', '1', '1', '1', '0', '512', '0', '', '', '0', '0', '0', '0', '0', '0', '0', 'npc_spelurk');
DELETE FROM `gameobject_template` WHERE `entry`='220815';  
INSERT INTO `gameobject_template` (`entry`, `type`, `displayId`, `name`, `IconName`, `castBarCaption`, `unk1`, `faction`, `flags`, `size`, `questItem1`, `questItem2`, `questItem3`, `questItem4`, `questItem5`, `questItem6`, `Data0`, `Data1`, `Data2`, `Data3`, `Data4`, `Data5`, `Data6`, `Data7`, `Data8`, `Data9`, `Data10`, `Data11`, `Data12`, `Data13`, `Data14`, `Data15`, `Data16`, `Data17`, `Data18`, `Data19`, `Data20`, `Data21`, `Data22`, `Data23`, `Data24`, `Data25`, `Data26`, `Data27`, `Data28`, `Data29`, `Data30`, `Data31`, `Data32`, `unkInt32`, `AIName`, `ScriptName`, `WorldEffectID`, `StateWorldEffectID`, `SpellVisualID`, `SpellStateVisualID`, `SpellStateAnimID`, `SpellStateAnimKitID`, `MaxVisible`, `IgnoreDynLos`, `MinGold`, `MaxGold`, `VerifiedBuild`) VALUES ('220815', '10', '2230', 'Cave-in', '', '', '', '0', '0', '1.5', '0', '0', '0', '0', '0', '0', '2133', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '', 'cave_in', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1');
DELETE FROM `gameobject` WHERE `id`='220815';