UPDATE quest_template_addon SET SourceSpellID = '52693' WHERE ID = '12687';
DELETE FROM quest_start_scripts WHERE id = '12687' AND delay = '0' AND command = '7' AND datalong = '12687' AND datalong2 = '0' AND dataint = '0' AND x = '0' AND y = '0' AND z = '0' AND o = '0';

-- Conditions generated by SAI-Editor
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=15 AND `SourceGroup`=61022 AND `SourceEntry`=0 AND ConditionValue1=29548;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`,`SourceGroup`,`SourceEntry`,`SourceId`,`ElseGroup`,`ConditionTypeOrReference`,`ConditionTarget`,`ConditionValue1`,`ConditionValue2`,`ConditionValue3`,`NegativeCondition`,`ErrorTextId`,`ScriptName`,`Comment`) VALUES
(15,61022,0,0,0,9,0,29548,0,0,0,0,"","");