UPDATE `custom_pvp_penalizations` SET `damage_penalization`='-5' WHERE (`specialization_id`='62') AND (`specialization_name`='Mago Arcano');
UPDATE `custom_pvp_penalizations` SET `damage_penalization`='5' WHERE (`specialization_id`='63') AND (`specialization_name`='Mago Fuego');
UPDATE `custom_pvp_penalizations` SET `damage_penalization`='-5' WHERE (`specialization_id`='64') AND (`specialization_name`='Mago Escarcha');
UPDATE `custom_pvp_penalizations` SET `healing_penalization`='-10' WHERE (`specialization_id`='65') AND (`specialization_name`='Paladin Sagrado');
UPDATE `custom_pvp_penalizations` SET `damage_penalization`='-5' WHERE (`specialization_id`='102') AND (`specialization_name`='Druida Equilibrio');
UPDATE `custom_pvp_penalizations` SET `mastery`='-10' WHERE (`specialization_id`='105') AND (`specialization_name`='Druida Restauracion');
UPDATE `custom_pvp_penalizations` SET `damage_penalization`='-12' WHERE (`specialization_id`='256') AND (`specialization_name`='Sacerdote Disciplina');
UPDATE `custom_pvp_penalizations` SET `healing_penalization`='-10' WHERE (`specialization_id`='257') AND (`specialization_name`='Sacerdote Sagrado');
UPDATE `custom_pvp_penalizations` SET `damage_penalization`='-10', `mastery`='-20' WHERE (`specialization_id`='258') AND (`specialization_name`='Sacerdote Sombra');
UPDATE `custom_pvp_penalizations` SET `damage_penalization`='-10' WHERE (`specialization_id`='262') AND (`specialization_name`='Shaman Elemental');
UPDATE `custom_pvp_penalizations` SET `mastery`='-20' WHERE (`specialization_id`='264') AND (`specialization_name`='Shaman Restauracion');
UPDATE `custom_pvp_penalizations` SET `damage_penalization`='-15', `mastery`='-30' WHERE (`specialization_id`='265') AND (`specialization_name`='Brujo Afliccion');
UPDATE `custom_pvp_penalizations` SET `damage_penalization`='-10', `mastery`='-5' WHERE (`specialization_id`='267') AND (`specialization_name`='Brujo Destruccion');
UPDATE `custom_pvp_penalizations` SET `healing_penalization`='-15' WHERE (`specialization_id`='270') AND (`specialization_name`='Monje Tejedor de la Niebla');

UPDATE `custom_pvp_penalizations` SET `damage_penalization`='-5', `healing_penalization`='-5' WHERE (`specialization_id`='66') AND (`specialization_name`='Paladin Proteccion');
UPDATE `custom_pvp_penalizations` SET `damage_penalization`='-15', `mastery`='-5' WHERE (`specialization_id`='70') AND (`specialization_name`='Paladin Retribucion');
UPDATE `custom_pvp_penalizations` SET `damage_penalization`='-15', `mastery`='-5' WHERE (`specialization_id`='71') AND (`specialization_name`='Warrior Arma');
UPDATE `custom_pvp_penalizations` SET `damage_penalization`='-15', `mastery`='-5' WHERE (`specialization_id`='72') AND (`specialization_name`='Warrior Furia');
UPDATE `custom_pvp_penalizations` SET `damage_penalization`='-5', `healing_penalization`='-5' WHERE (`specialization_id`='73') AND (`specialization_name`='Warrior Proteccion');
UPDATE `custom_pvp_penalizations` SET `mastery`='-15' WHERE (`specialization_id`='103') AND (`specialization_name`='Druida Feral');
UPDATE `custom_pvp_penalizations` SET `damage_penalization`='-5', `healing_penalization`='-5' WHERE (`specialization_id`='104') AND (`specialization_name`='Druida Guardian');
UPDATE `custom_pvp_penalizations` SET `damage_penalization`='-5', `healing_penalization`='-5' WHERE (`specialization_id`='250') AND (`specialization_name`='Caballero de la Muerte Sangre');
UPDATE `custom_pvp_penalizations` SET `damage_penalization`='-15', `mastery`='-5' WHERE (`specialization_id`='251') AND (`specialization_name`='Caballero de la Muerte Escarcha');
UPDATE `custom_pvp_penalizations` SET `damage_penalization`='0', `mastery`='-15' WHERE (`specialization_id`='252') AND (`specialization_name`='Caballero de la Muerte Profano');
UPDATE `custom_pvp_penalizations` SET `mastery`='-15' WHERE (`specialization_id`='253') AND (`specialization_name`='Hunter Bestia');
UPDATE `custom_pvp_penalizations` SET `mastery`='-30' WHERE (`specialization_id`='254') AND (`specialization_name`='Hunter Punteria');
UPDATE `custom_pvp_penalizations` SET `damage_penalization`='-5' WHERE (`specialization_id`='255') AND (`specialization_name`='Hunter Supervivencia');
UPDATE `custom_pvp_penalizations` SET `damage_penalization`='-7' WHERE (`specialization_id`='260') AND (`specialization_name`='Picaro Forajido');
UPDATE `custom_pvp_penalizations` SET `damage_penalization`='-10', `mastery`='-15' WHERE (`specialization_id`='259') AND (`specialization_name`='Picaro Asesinato');
UPDATE `custom_pvp_penalizations` SET `damage_penalization`='-15', `mastery`='-5' WHERE (`specialization_id`='263') AND (`specialization_name`='Shaman Mejora');
UPDATE `custom_pvp_penalizations` SET `damage_penalization`='-5', `healing_penalization`='-5' WHERE (`specialization_id`='268') AND (`specialization_name`='Monje Maestro Cervecero');
UPDATE `custom_pvp_penalizations` SET `damage_penalization`='-15', `mastery`='-5' WHERE (`specialization_id`='577') AND (`specialization_name`='Cazador de Demonio Destruccion');
UPDATE `custom_pvp_penalizations` SET `damage_penalization`='-5', `healing_penalization`='-5' WHERE (`specialization_id`='581') AND (`specialization_name`='Cazador de Demonio Venganza');
UPDATE `custom_pvp_penalizations` SET `damage_penalization`='-10' WHERE (`specialization_id`='269') AND (`specialization_name`='Monje Caminaviento');
UPDATE `custom_pvp_penalizations` SET `damage_penalization`='-10' WHERE (`specialization_id`='260') AND (`specialization_name`='Picaro Forajido');