/* parte 1 david XD */
UPDATE `creature_text` SET `Text`="Welcome to my temporary refuge and your grave! You are late, the artifact is no longer here, and soon you will not be ..." WHERE (`entry`='200403' AND `GroupID`='0');
UPDATE `creature_text` SET `Text`="I think even the most stupid of you have already guessed that I’m not the one I pretend to be. This masquerade is useless." WHERE (`entry`='200403' AND `GroupID`='1');
UPDATE `creature_text` SET `Text`="I completed the plan. Lured you, heroes, to a false trail, now no one will interfere with the destruction of the artifact! The one you hope for will destroy you ..." WHERE (`entry`='200403' AND `GroupID`='2');
UPDATE `creature_text` SET `Text`="Your remains make good toys." WHERE (`entry`='200403' AND `GroupID`='3');
UPDATE `creature_text` SET `Text`="Do not get close! I do not want to hurt you!" WHERE (`entry`='200404' AND `GroupID`='0');
UPDATE `creature_text` SET `Text`="Run! Otherwise you will freeze ..." WHERE (`entry`='200404' AND `GroupID`='1');
UPDATE `creature_text` SET `Text`="I'm sorry. I do not want to do this, but I can not resist ..." WHERE (`entry`='200404' AND `GroupID`='2');
UPDATE `creature_text` SET `Text`="Grandfather Zima defended himself with ice and prepare to use a powerful spell to destroy the artifact. All living things in a large radius will perish!" WHERE (`entry`='200404' AND `GroupID`='3');
UPDATE `creature_text` SET `Text`="Albond damn you! It was necessary to destroy you!" WHERE (`entry`='200407' AND `GroupID`='0');
UPDATE `creature_text` SET `Text`="But nothing, my time will come yet, and then you will all fall before me." WHERE (`entry`='200407' AND `GroupID`='1');
UPDATE `creature_text` SET `Text`="Finally, I woke up and have the right to control myself." WHERE (`entry`='200408' AND `GroupID`='0');
UPDATE `creature_text` SET `Text`="Thanks friends! Thanks Albond! What would I do without you, the damned demon captured my mind, I could not resist it." WHERE (`entry`='200408' AND `GroupID`='1');
UPDATE `creature_text` SET `Text`="Metzen, how I miss you!" WHERE (`entry`='200408' AND `GroupID`='2');
UPDATE `creature_text` SET `Text`="I want to thank you for what you have done for me and all the inhabitants of Azeroth. Take gifts, they are waiting for you!" WHERE (`entry`='200408' AND `GroupID`='3');
UPDATE `creature_text` SET `Text`="Mistake!" WHERE (`entry`='35486' AND `GroupID`='0');
UPDATE `creature_text` SET `Text`="To move to Vashj'ir, speak with me again." WHERE (`entry`='36799' AND `GroupID`='0');
UPDATE `creature_text` SET `Text`="Phew, some supplies are completely wet and ... some sticky. It can be used, but they look disgusting." WHERE (`entry`='77209' AND `GroupID`='3');
UPDATE `creature_text` SET `Text`="Tear the decks until they sparkle, pathetic sacks of bones. Admiral of Horror requires everything to be perfect." WHERE (`entry`='102185' AND `GroupID`='0');
UPDATE `creature_text` SET `Text`="Great choice. And now I will dedicate you to the details of our plan." WHERE (`entry`='94159' AND `GroupID`='0');
UPDATE `creature_text` SET `Text`="The message is secret. Read it and destroy it immediately." WHERE (`entry`='102018' AND `GroupID`='0');
UPDATE `creature_text` SET `Text`="$n, can I have you a minute? Urgent message." WHERE (`entry`='102018' AND `GroupID`='1');
UPDATE `creature_text` SET `Text`="We only need to talk briefly with the eredar ... alone. He has the information we need." WHERE (`entry`='94902' AND `GroupID`='0');
UPDATE `creature_text` SET `Text`="I step into the abyss!" WHERE (`entry`='97083' AND `GroupID`='0');
UPDATE `creature_text` SET `Text`="Dragons, come to my aid!" WHERE (`entry`='94960' AND `GroupID`='1' AND `id` =1);
UPDATE `creature_text` SET `Text`="Praise the Light, $ n, I found you. We need to talk urgently." WHERE (`entry`='92909' AND `GroupID`='0');
UPDATE `creature_text` SET `Text`="To me, demon hunters. I will give you unprecedented power!" WHERE (`entry`='96682' AND `GroupID`='0');
UPDATE `creature_text` SET `Text`="The guards would leave us here to rot until the end of time. Why are you on their side?" WHERE (`entry`='96682' AND `GroupID`='1');
UPDATE `creature_text` SET `Text`="No ... No, no! Fools." WHERE (`entry`='96682' AND `GroupID`='3');
UPDATE `creature_text` SET `Text`="You all heard what the Sentinel said. Only we can defeat the Legion. We MUST get out of here alive." WHERE (`entry`='96665' AND `GroupID`='1');
UPDATE `creature_text` SET `Text`="And are they the defenders of this world? Sorry sight." WHERE (`entry`='92776' AND `GroupID`='4');
UPDATE `creature_text` SET `Text`="This device feeds the energy of the Abyss, which was released when Malygos sent the lines of force of Azeroth to the Twisting Nether." WHERE (`entry`='105917' AND `ID`='0');
UPDATE `creature_text` SET `Text`="This weapon is defiled by the energy of the Circular Nether." WHERE (`entry`='105917' AND `ID`='2');
UPDATE `creature_text` SET `Text`="This IS similar TO the ether portals IN Outland." WHERE (`entry`='105917' AND `ID`='1');
UPDATE `creature_text` SET `Text`="This is just crazy! The guards do not control their own prison." WHERE (`entry`='97643' AND `GroupID`='0');
UPDATE `creature_text` SET `Text`="Kayn and Altruis have already gone upstairs. Saddle this felbat and catch up with them." WHERE (`entry`='97070' AND `GroupID`='0');
UPDATE `creature_text` SET `Text`="I hope Maiev didn’t make the mistake of freeing you, $demon hunter:demon hunter;. Go ahead, I will delay the enemy." WHERE (`entry`='96847' AND `GroupID`='0');
UPDATE `creature_text` SET `Text`="Why should Maiev free us? There can be only one reason for this ..." WHERE (`entry`='92980' AND `GroupID`='0');
UPDATE `creature_text` SET `Text`="Demons want to destroy our world. We must free our allies." WHERE (`entry`='92980' AND `GroupID`='1');
UPDATE `creature_text` SET `Text`="$n, this power ... overwhelms me." WHERE (`entry`='96652' AND `GroupID`='0');
UPDATE `creature_text` SET `Text`="Lord Gul'dan will lead us to victory. You won’t stop us!" WHERE (`entry`='97069' AND `GroupID`='0');
UPDATE `creature_text` SET `Text`="Demonic energy ... I feel how I have become stronger." WHERE (`entry`='96655' AND `GroupID`='1');
UPDATE `creature_text` SET `Text`="Nothing! Who believes the Guardians? More than us, she hates only the Legion." WHERE (`entry`='92986' AND `GroupID`='2');
UPDATE `creature_text` SET `Text`="$n, the creature’s destructive ray is pointed at me. Change the position of the last mirror to split his shield!" WHERE (`entry`='102391' AND `GroupID`='0');
UPDATE `creature_text` SET `Text`="The shield is broken! Rather leave before this creature has come to its senses!" WHERE (`entry`='102391' AND `GroupID`='1');
UPDATE `creature_text` SET `Text`="I'll be waiting for you at the gate on the Red-hot Shore." WHERE (`entry`='100982' AND `GroupID`='0');
UPDATE `creature_text` SET `Text`="You do me honor ..." WHERE (`entry`='99915' AND `GroupID`='1');
UPDATE `creature_text` SET `Text`="I want to stop Gul'dan, and for this I need your help. Rather free the other illidari!" WHERE (`entry`='92718' AND `GroupID`='1');
UPDATE `creature_text` SET `Text`="The mother of demons is right in this cave." WHERE (`entry`='98711' AND `GroupID`='0');
UPDATE `creature_text` SET `Text`="Go to Seed of Ages, High Druid. There we will reveal all the secrets of your weapons." WHERE (`entry`='101195' AND `GroupID`='1');
UPDATE `creature_text` SET `Text`="TRaven Crest will not give up! We will win again!" WHERE (`entry`='93031' AND `GroupID`='0');
UPDATE `creature_text` SET `Text`="So, be your way! If necessary, I will chase you around the city!" WHERE (`entry`='98519' AND `GroupID`='5');
UPDATE `creature_text` SET `Text`="Sorry for such secrecy - an old habit. My name is Alonsy Faol. In my life I have been able to visit both the head of the church, the brainless servant of the Scourge, and the organizer of a secret war. But first of all, I have always been and remain a priest." WHERE (`entry`='101314' AND `GroupID`='0');
UPDATE `creature_text` SET `Text`="Val'kyr is approaching! We should respectfully greet her. Come out, heroes!" WHERE (`entry`='97166' AND `GroupID`='0');
UPDATE `creature_text` SET `Text`="Welcome to the Halls of Valor, where daredevils live forever!" WHERE (`entry`='93823' AND `GroupID`='0');
UPDATE `creature_text` SET `Text`="Behind you is the Eye of Odin, who sees all of Azeroth! And on the other side is the forge, where Helgar, the greatest blacksmith, forges the most powerful weapon for the Valariars." WHERE (`entry`='93823' AND `GroupID`='1');
UPDATE `creature_text` SET `Text`="One is waiting ahead. I will go and announce your arrival. Do not forget about respect." WHERE (`entry`='93823' AND `GroupID`='3');
UPDATE `creature_text` SET `Text`="And that’s all that you $capable of:capable of ,? Will have to try better. Will not work." WHERE (`entry`='92243' AND `GroupID`='0');
UPDATE `creature_text` SET `Text`="|3-6($ct) $n, we urgently need to talk!" WHERE (`entry`='99343' AND `GroupID`='1');
UPDATE `creature_text` SET `Text`="You, of course, have heard of $glegendary:legendary; |3-5 $p), $gwho proved with her deeds that she is worthy:she proved with her deeds that she is worthy; wear the Ashtray and take the place of Tyrion in the order as $gHighlord:High Lady;. Now that $ p is leading us, we can give the Legion a fitting rebuff." WHERE (`entry`='91866' AND `GroupID`='0');
UPDATE `creature_text` SET `Text`="I have not seen him, but he is the one we are looking for. Local kvaldirs are afraid of a huge cat that settled in the swamps. They erected watch stones that block the path not only to her, but to us." WHERE (`entry`='99958' AND `GroupID`='0');
UPDATE `creature_text` SET `Text`="This secrecy infuriates me! Someone throw a rocket!" WHERE (`entry`='100235' AND `GroupID`='3');
UPDATE `creature_text` SET `Text`="These ghosts are hiding in the shadows! Does anyone have a light rocket?" WHERE (`entry`='100235' AND `GroupID`='4');
UPDATE `creature_text` SET `Text`="The monster hid in a thick fog. It can be anywhere. Do you have a trap powerful enough to hold the creature until we kill it?" WHERE (`entry`='100235' AND `GroupID`='6');
UPDATE `creature_text` SET `Text`="The monster attacks us from the fog! Hurry!" WHERE (`entry`='100235' AND `GroupID`='7');
UPDATE `creature_text` SET `Text`="Hold them until the trap fires!" WHERE (`entry`='100235' AND `GroupID`='8');
UPDATE `creature_text` SET `Text`="We ... Wow! Not!" WHERE (`entry`='100235' AND `GroupID`='11');
UPDATE `creature_text` SET `Text`="Brother ... Eh, it was not necessary to take you with you." WHERE (`entry`='100235' AND `GroupID`='12');
UPDATE `creature_text` SET `Text`="I will avenge you. We have to get to the end. Follow the trail of the monster." WHERE (`entry`='100235' AND `GroupID`='13');
UPDATE `creature_text` SET `Text`="My wounds ... won't heal. We must quickly end the monster." WHERE (`entry`='100235' AND `GroupID`='14');
UPDATE `creature_text` SET `Text`="We won’t be able to fight back until you set a trap! Hurry!" WHERE (`entry`='100235' AND `GroupID`='15');
UPDATE `creature_text` SET `Text`="Just not that! Watch out!" WHERE (`entry`='100235' AND `GroupID`='20');
UPDATE `creature_text` SET `Text`="I ... reached the end of the trail ... then you have to go $one:one;." WHERE (`entry`='100235' AND `GroupID`='21');
UPDATE `creature_text` SET `Text`="We have to get through somehow! Wooho, tell me everything you know while $gis our ally: our ally; inspects the port. $n, if you want, I will tell you everything I know." WHERE (`entry`='99374' AND `GroupID`='1');
UPDATE `creature_text` SET `Text`="The Invisible Path will become even stronger than before!" WHERE (`entry`='102578' AND `GroupID`='4');
UPDATE `creature_text` SET `Text`="Do not be afraid. By the power of Ulthalesh in death, you will be more powerful than you were in life." WHERE (`entry`='100388' AND `GroupID`='1');
UPDATE `creature_text` SET `Text`="The blade was moved somewhere to the northwestern part of Tirisfal. I marked on your map a place where you should start your search." WHERE (`entry`='101314' AND `GroupID`='3');
UPDATE `creature_text` SET `Text`="Fine. In the presence of the greatest mages of Azeroth, I name you $n, $gSorcerer: Sorceress; Guardians of Tirisfal." WHERE (`entry`='102700' AND `GroupID`='8');
UPDATE `creature_text` SET `Text`="Mages of Azeroth! I gathered you here in the face of a threat to our entire world!" WHERE (`entry`='102700' AND `GroupID`='3');
UPDATE `creature_text` SET `Text`="Come to us in Freedom Circle, $gWarlock: Warlock ;. My portal will take you straight there. We will wait." WHERE (`entry`='103506' AND `GroupID`='0');
UPDATE `creature_text` SET `Text`="Hi, $n. I finally managed to find you. They are waiting for you at Moonglade." WHERE (`entry`='101061' AND `GroupID`='0');
UPDATE `creature_text` SET `Text`="Good! This seed contains magic from the time when the world was young. As you will soon see with your own eyes, this will be very useful to us." WHERE (`entry`='97923' AND `GroupID`='0');
UPDATE `creature_text` SET `Text`="The strength of your weapons is great. And she will continue to grow with yours" WHERE (`entry`='97923' AND `GroupID`='1');
UPDATE `creature_text` SET `Text`="You fight, and I will repair. Come on, get on the tank!" WHERE (`entry`='80886' AND `GroupID`='0');
UPDATE `creature_text` SET `Text`="My branches will grow back, but your arms and legs will not." WHERE (`entry`='103344' AND `GroupID`='2' AND `ID` ='1');
UPDATE `creature_text` SET `Text`="I'll break you like brushwood." WHERE (`entry`='103344' AND `GroupID`='2'AND `ID` ='0');
UPDATE `creature_text` SET `Text`="My bark is your doom." WHERE (`entry`='103344' AND `GroupID`='0'AND `ID` ='0');
UPDATE `creature_text` SET `Text`="Let me know when you will be $ got ready: ready ;! And together we will go to save the Guardian of Remulus!" WHERE (`entry`='220034' AND `GroupID`='1');
UPDATE `creature_text` SET `Text`="Jabrul will be waiting for you in the night elf house. Come to him when you are $ready:ready ,." WHERE (`entry`='100860' AND `GroupID`='7');
UPDATE `creature_text` SET `Text`="And according to my plan, the truly great priest should lead this council, by his actions he won the glory of the hero not only among his own, but everywhere. I believe that you are the very hero: that heroine; but you will also need to convince others of this. You are $ready:ready; to the tests?" WHERE (`entry`='101314' AND `GroupID`='2');
UPDATE `creature_text` SET `Text`="Okayushki." WHERE (`entry`='86775' AND `GroupID`='0');
UPDATE `creature_text` SET `Text`="Yes, Leader. So, I removed the Forsaken from their curse!" WHERE (`entry`='44365' AND `GroupID`='5');
UPDATE `creature_text` SET `Text`="Buoy strong, baby. I will keep an eye on you." WHERE (`entry`='75005' AND `GroupID`='4');
UPDATE `creature_text` SET `Text`="The poison is not made by you. Tell me who made it, and for you everything can end." WHERE (`entry`='83706' AND `GroupID`='1' AND `ID` ='2');
UPDATE `creature_text` SET `Text`="Who led the raid on the Arak? Where is he hiding?" WHERE (`entry`='83706' AND `GroupID`='1' AND `ID` ='0');
UPDATE `creature_text` SET `Text`="The poison is not made by you. Tell me who made it, and for you everything can end." WHERE (`entry`='83760' AND `GroupID`='1' AND `ID` ='2');
UPDATE `creature_text` SET `Text`="Do not think that you won ..." WHERE (`entry`='71504' AND `GroupID`='5');
UPDATE `creature_text` SET `Text`="Compatible business with pleasure" WHERE (`entry`='71504' AND `GroupID`='0');
UPDATE `creature_text` SET `Text`="My legacy ... will live on ..." WHERE (`entry`='71504' AND `GroupID`='6');
UPDATE `creature_text` SET `Text`="I'll take him away from here." WHERE (`entry`='72438' AND `GroupID`='1');
UPDATE `creature_text` SET `Text`="And ... the hunter ... became prey .." WHERE (`entry`='71153' AND `GroupID`='5');
UPDATE `creature_text` SET `Text`="Are my calculations wrong? Maybe after another 800 years." WHERE (`entry`='71160' AND `GroupID`='15');
UPDATE `creature_text` SET `Text`="Bring me back ... to amber .." WHERE (`entry`='71155' AND `GroupID`='12');
UPDATE `creature_text` SET `Text`="Meet me in suramar, hero! I will be waiting for you in the menagerie." WHERE (`entry`='106897' AND `GroupID`='1');
UPDATE `creature_text` SET `Text`="Let everyone know about our victory. Fly to the garrison on the magic dragon. See you!" WHERE (`entry`='73395' AND `GroupID`='5');
UPDATE `creature_text` SET `Text`="Telin? What are you doing here?" WHERE (`entry`='80978' AND `GroupID`='1');
UPDATE `creature_text` SET `Text`="Who led the raid on the Arak? Where is he hiding?" WHERE (`entry`='83749' AND `GroupID`='5' AND `ID` ='0');
UPDATE `creature_text` SET `Text`="Give me the shackles, I will turn their strength against the Firelord and his servants. You will receive a reward for this." WHERE (`entry`='110990' AND `GroupID`='4');
UPDATE `creature_text` SET `Text`="I escaped from Val'shara when Ysera attacked the temple. I was very lucky that along the way we met with Mitandros." WHERE (`entry`='103568' AND `GroupID`='1');
UPDATE `creature_text` SET `Text`="Do you dare to challenge our power ?!" WHERE (`entry`='77024' AND `GroupID`='2');
UPDATE `creature_text` SET `Text`="What do you think, someone will give you something for a great life? Sorry, honey, but service for service." WHERE (`entry`='96979' AND `GroupID`='1' AND `ID`= '1');
UPDATE `creature_text` SET `Text`="Let's just say that I do not have love for Tikhondria. And my lord ... the fall of the Legion is profitable" WHERE (`entry`='47733' AND `GroupID`='4');
UPDATE `creature_text` SET `Text`="The poison is not made by you. Tell me who made it, and for you everything can end." WHERE (`entry`='83749' AND `GroupID`='5' AND `ID` ='2');
UPDATE `creature_text` SET `Text`="Come out, Taerar! I stand in front of you!" WHERE (`entry`='39407' AND `GroupID`='1');
UPDATE `creature_text` SET `Text`="Yes, this place." WHERE (`entry`='48044' AND `GroupID`='1');
UPDATE `creature_text` SET `Text`="I decided that this warlock can be trusted. He can freely move around the temple." WHERE (`entry`='168137' AND `GroupID`='3');
UPDATE `creature_text` SET `Text`="And you weren’t in a hurry!: In a hurry !; What, apparently, on the way back stopped to miss a mug? Okay, here's the scrap for you, as we agreed." WHERE (`entry`='96979' AND `GroupID`='4');
UPDATE `creature_text` SET `Text`="Murder in a union city is too risky, but if you slaughter a homunculus in Silvermoon, there will be no questions. And we will take care of the goals in Exodar." WHERE (`entry`='98099' AND `GroupID`='10');
UPDATE `creature_text` SET `Text`="Deathwing leans to the right!" WHERE (`entry`='600034' AND `GroupID`='3');
UPDATE `creature_text` SET `Text`="He's going to tilt to the right!" WHERE (`entry`='600034' AND `GroupID`='2');
UPDATE `creature_text` SET `Text`="Deathwing feels the players on its right side." WHERE (`entry`='600034' AND `GroupID`='1');
UPDATE `creature_text` SET `Text`="Deathwing leans to the left!" WHERE (`entry`='600034' AND `GroupID`='4');
UPDATE `creature_text` SET `Text`="Deathwing leans to the left!" WHERE (`entry`='600033' AND `GroupID`='3');
UPDATE `creature_text` SET `Text`="Deathwing leans to the left!" WHERE (`entry`='600033' AND `GroupID`='3');
UPDATE `creature_text` SET `Text`="He's going to tilt to the left!" WHERE (`entry`='600033' AND `GroupID`='2');
UPDATE `creature_text` SET `Text`="Deathwing feels the players on its left side." WHERE (`entry`='600033' AND `GroupID`='1');
UPDATE `creature_text` SET `Text`="Your time has come, Kromgak! Release your inner strength!" WHERE (`entry`='111826' AND `GroupID`='2');
UPDATE `creature_text` SET `Text`="Who led the raid on the Arak? Where is he hiding.?" WHERE (`entry`='83760' AND `GroupID`='1' AND`ID` = '0');
UPDATE `creature_text` SET `Text`="Another Warlock? After what happened last time, you should be glad that we did not kill you right away." WHERE (`entry`='68096' AND `GroupID`='2');
UPDATE `creature_text` SET `Text`="Fighting Veterans may remember Blat's self-replicating slurry. Today I present to you his even more evil and terrible older sister - Bulk!" WHERE (`entry`='68323' AND `GroupID`='19');
UPDATE `creature_text` SET `Text`="This side of the portal is now completely under our control." WHERE (`entry`='102977' AND `GroupID`='0');
UPDATE `creature_text` SET `Text`="What? Stranger! You will not stop me, Frostmourne will be mine!" WHERE (`entry`='93963' AND `GroupID`='1');
UPDATE `creature_text` SET `Text`="Feel the piercing cold of death!" WHERE (`entry`='93963' AND `GroupID`='3');
UPDATE `creature_text` SET `Text`="Aah! Darkness, I can’t ... I ..." WHERE (`entry`='93963' AND `GroupID`='4');
UPDATE `creature_text` SET `Text`="Only ... darkness ..." WHERE (`entry`='93963' AND `GroupID`='6');
UPDATE `creature_text` SET `Text`="Arthas Menethil. Take the blade, fulfill your destiny!" WHERE (`entry`='94982' AND `GroupID`='0');
UPDATE `creature_text` SET `Text`="Who dares to intervene ?! His soul belongs to ME!" WHERE (`entry`='94982' AND `GroupID`='1');
UPDATE `creature_text` SET `Text`="AOh, with a triumphant return! You had to make a lot of efforts to learn everything that I taught you." WHERE (`entry`='97132' AND `GroupID`='0');
UPDATE `creature_text` SET `Text`="Gargoyles take off, nothing else presses on pressure plates, and lowering grates block the course!" WHERE (`entry`='97320' AND `GroupID`='0');
UPDATE `creature_text` SET `Text`="There may not be a king anymore, but I will never leave Lordaeron!" WHERE (`entry`='93949' AND `GroupID`='0');
UPDATE `creature_text` SET `Text`="Wow ... Do you really think that your Light of heaven will protect you from the Legion?" WHERE (`entry`='100388' AND `GroupID`='2');
UPDATE `creature_text` SET `Text`="With your worthless lives, I will pave the way for the Legion!" WHERE (`entry`='100388' AND `GroupID`='5');
UPDATE `creature_text` SET `Text`="The Legion is a threat that cannot be ignored, so I decided to go out of the shadows again. Now I am gathering all the clergy to work out a joint plan to counter this threat." WHERE (`entry`='101314' AND `GroupID`='1');
UPDATE `creature_text` SET `Text`="He is inside. I ask you, do everything possible to save him." WHERE (`entry`='105602' AND `GroupID`='1');
UPDATE `creature_text` SET `Text`="Oh my head ... Where am I?" WHERE (`entry`='105586' AND `GroupID`='3');
UPDATE `creature_text` SET `Text`="I'll go with you. You helped one of mine, so I will repay you with a service for the service." WHERE (`entry`='105602' AND `GroupID`='3');
UPDATE `creature_text` SET `Text`="Meet me at the Krasa site and fly to the island on my griffin." WHERE (`entry`='105602' AND `GroupID`='4');
UPDATE `creature_text` SET `Text`="Impossible ... I'm ... the best .." WHERE (`entry`='104881' AND `GroupID`='8');
UPDATE `creature_text` SET `Text`="Do you still reject my gift?" WHERE (`entry`='105393' AND `GroupID`='2');
UPDATE `creature_text` SET `Text`="As a result of your movements, the ice block has cracked!" WHERE (`entry`='99605' AND `GroupID`='0');
UPDATE `creature_text` SET `Text`="Horrorlord Katra'natir fled to the Twisting Nether, taking with him the secrets of the Council of Tirisfal." WHERE (`entry`='102700' AND `GroupID`='4');
UPDATE `creature_text` SET `Text`="To this end, I restore the Order of the Guardians of Tirisfal. And I urge you to join us and raise weapons against the Legion! Are you with us ?!" WHERE (`entry`='102700' AND `GroupID`='6');
UPDATE `creature_text` SET `Text`="Come to me, my fellow demon! I climbed high with you!" WHERE (`entry`='94714' AND `GroupID`='5');
UPDATE `creature_text` SET `Text`="Let it be so. Come on, my wounded friends. Let's see if I have the strength to bring you to a safe place." WHERE (`entry`='106153' AND `GroupID`='0');
UPDATE `creature_text` SET `Text`="I will lead you to Prince Farondis, as you wish." WHERE (`entry`='89402' AND `GroupID`='0');
UPDATE `creature_text` SET `Text`="Spit on him for me at a meeting." WHERE (`entry`='89402' AND `GroupID`='1');
UPDATE `creature_text` SET `Text`="Spray and sand!" WHERE (`entry`='89284' AND `GroupID`='0' AND `ID`='0');
UPDATE `creature_text` SET `Text`="Look! They go to grandfather's pond!" WHERE (`entry`='107995' AND `GroupID`='0');
UPDATE `creature_text` SET `Text`="Hunger overshadowed my mind. I can no longer restrain myself. I'm like, like ..." WHERE (`entry`='91131' AND `GroupID`='0');
UPDATE `creature_text` SET `Text`="I ... I don't see you." WHERE (`entry`='91131' AND `GroupID`='2');
UPDATE `creature_text` SET `Text`="Probably ... we have to say goodbye." WHERE (`entry`='91131' AND `GroupID`='3');
UPDATE `creature_text` SET `Text`="Now my last hours have not passed in vain." WHERE (`entry`='91131' AND `GroupID`='4');
UPDATE `creature_text` SET `Text`="Hurry up, Minerva. We have to get out of here. Mograine will rip off our living skin from us if we detain everyone." WHERE (`entry`='95904' AND `GroupID`='0');
UPDATE `creature_text` SET `Text`="It is foolish to think that such an insignificant detachment can withstand the right hand of Sargeras!" WHERE (`entry`='100388' AND `GroupID`='4');
UPDATE `creature_text` SET `Text`="This is $gpriest:priestess; praise to the Light!" WHERE (`entry`='105602' AND `GroupID`='0');
UPDATE `creature_text` SET `Text`="Defilers! We must destroy these creatures!" WHERE (`entry`='96468' AND `GroupID`='18');
UPDATE `creature_text` SET `Text`="Can not wait." WHERE (`entry`='96663' AND `GroupID`='0');
UPDATE `creature_text` SET `Text`="A dream always shows the truth - and he showed me your doom." WHERE (`entry`='102672' AND `GroupID`='82');
UPDATE `creature_text` SET `Text`="Breathe deeper. Accept fate." WHERE (`entry`='102672' AND `GroupID`='49');
UPDATE `creature_text` SET `Text`="The dream has changed, but I will still protect it." WHERE (`entry`='102672' AND `GroupID`='45');
UPDATE `creature_text` SET `Text`="Sleep well. New Dream will transform your world ..." WHERE (`entry`='102672' AND `GroupID`='24');
UPDATE `creature_text` SET `Text`="You don't need this life anymore!" WHERE (`entry`='102672' AND `GroupID`='19');
UPDATE `creature_text` SET `Text`="Waking is a disease!" WHERE (`entry`='102672' AND `GroupID`='20');
UPDATE `creature_text` SET `Text`="Defender! Here is Brett, the messenger of your doom." WHERE (`entry`='105399' AND `GroupID`='0');
UPDATE `creature_text` SET `Text`="Eyir! Watch me fight this pathetic  defender " WHERE (`entry`='105399' AND `GroupID`='1');
UPDATE `creature_text` SET `Text`="There is a sign of a dark lily ... Seal of the first witch! So is she alive?" WHERE (`entry`='101499' AND `GroupID`='3');
UPDATE `creature_text` SET `Text`="Here it is, my old sanctuary..!" WHERE (`entry`='101852' AND `GroupID`='0' AND `BroadcastTextID` ='0');
UPDATE `creature_text` SET `Text`="Now, these coils draw the energy of the lines of force. Turn it on.!" WHERE (`entry`='101852' AND `GroupID`='3' AND `BroadcastTextID` ='0');
UPDATE `creature_text` SET `Text`="Good. If we overload enough rings, the whole system will be cut down" WHERE (`entry`='101852' AND `GroupID`='4'AND `BroadcastTextID` ='0');
UPDATE `creature_text` SET `Text`="In the lower hall there are still coils ... And, it seems, strangers again" WHERE (`entry`='101852' AND `GroupID`='5'AND `BroadcastTextID` ='0');
UPDATE `creature_text` SET `Text`="I’ll deal with Twain. Overload the coils!." WHERE (`entry`='101852' AND `GroupID`='7' AND `BroadcastTextID` = '0');
UPDATE `creature_text` SET `Text`="Monument to our father a little further, around the corner. Anaris is probably somewhere nearby." WHERE (`entry`='105342' AND `GroupID`='2');
UPDATE `creature_text` SET `Text`="Mornat says: Okay, take it! Just don't hit me anymore. The chest over there." WHERE (`entry`='104369' AND `GroupID`='1');
UPDATE `creature_text` SET `Text`="Does he dare to send someone in his place? Scoundrel." WHERE (`entry`='104394' AND `GroupID`='0');
UPDATE `creature_text` SET `Text`="Talisra alive? I'm going, let's talk together." WHERE (`entry`='104998' AND `GroupID`='0');
UPDATE `creature_text` SET `Text`="The stars judged you and considered you a jerk." WHERE (`entry`='103758' AND `GroupID`='9');
UPDATE `creature_text` SET `Text`="Go back to nothing." WHERE (`entry`='103758' AND `GroupID`='10');
UPDATE `creature_text` SET `Text`="Would you know what's next ..." WHERE (`entry`='103758' AND `GroupID`='13');
UPDATE `creature_text` SET `Text`="Your armor protects from blades and claws, but it is useless in battle with faceless. They drive mortals crazy with their whispers." WHERE (`entry`='102282' AND `GroupID`='0');
UPDATE `creature_text` SET `Text`="Get an ice fist!" WHERE (`entry`='108879' AND `GroupID`='2');
UPDATE `creature_text` SET `Text`="I had to run! Now your crows will bite your bones!" WHERE (`entry`='100497' AND `GroupID`='0');
UPDATE `creature_text` SET `Text`="Uh ... I was just ... looking for new dyes for the fabric. Yes Yes. New dyes. I will be right back at the studio." WHERE (`entry`='93967' AND `GroupID`='1');
UPDATE `creature_text` SET `Text`="Dream work vi-" WHERE (`entry`='91109' AND `GroupID`='1');
UPDATE `creature_text` SET `Text`="Malfurion! Thanks to Elune!" WHERE (`entry`='91651' AND `GroupID`='0');
UPDATE `creature_text` SET `Text`="Hurry! Something happened!" WHERE (`entry`='91651' AND `GroupID`='1');
UPDATE `creature_text` SET `Text`="He went to Dream, but cannot get out of it." WHERE (`entry`='91651' AND `GroupID`='2');
UPDATE `creature_text` SET `Text`="We don’t know yet." WHERE (`entry`='91651' AND `GroupID`='3');
UPDATE `creature_text` SET `Text`="Ah, Val'sharah ..." WHERE (`entry`='91465' AND `GroupID`='1');
UPDATE `creature_text` SET `Text`="Druids once created Val'sharah as a reflection of the Emerald Dream." WHERE (`entry`='91465' AND `GroupID`='3');
UPDATE `creature_text` SET `Text`="that land is a real echo of the Emerald Dream in our world." WHERE (`entry`='91465' AND `GroupID`='4');
UPDATE `creature_text` SET `Text`="Get ready, soon we will appear before the Lord of the Forest." WHERE (`entry`='91465' AND `GroupID`='5');
UPDATE `creature_text` SET `Text`="This place has no power over you ... I envy!" WHERE (`entry`='100497' AND `GroupID`='6');
UPDATE `creature_text` SET `Text`="Yes ... You're right ... I will accept any curse to take revenge ..." WHERE (`entry`='93963' AND `GroupID`='0');
UPDATE `creature_text` SET `Text`="I'm tired of these games. Speak - or you will die" WHERE (`entry`='117622' AND `GroupID`='0' AND `BroadcastTextID` ='0');
UPDATE `creature_text` SET `Text`="Thank you! And now I will kill the Sentinel, who set it up." WHERE (`entry`='90546' AND `GroupID`='1');
UPDATE `creature_text` SET `Text`="Mac'Ari ... lies in ruins..." WHERE (`entry`='128725' AND `GroupID`='0' AND `BroadcastTextID` ='0');
UPDATE `creature_text` SET `Text`="L'ura ..." WHERE (`entry`='120533' AND `GroupID`='0');
UPDATE `creature_text` SET `Text`="Before death, you will give me all the secrets" WHERE (`entry`='120896' AND `GroupID`='0' AND `ID` ='3');
UPDATE `creature_text` SET `Text`="My reward ... my burden ..." WHERE (`entry`='107959' AND `GroupID`='6');
UPDATE `creature_text` SET `Text`="Thank you I will return to the break of the Evil Scar myself." WHERE (`entry`='104941' AND `GroupID`='0');
UPDATE `creature_text` SET `Text`="Lively, get in the gondola!" WHERE (`entry`='115018' AND `GroupID`='1');
UPDATE `creature_text` SET `Text`="You $gspas:saved; me! I will not forget this!" WHERE (`entry`='105794' AND `GroupID`='0' AND `ID` ='1');
UPDATE `creature_text` SET `Text`="Thank! It feels like I've been here forever." WHERE (`entry`='108672' AND `GroupID`='0');
UPDATE `creature_text` SET `Text`="It seems that fate was pleased to bring us together again, |3-6($c)." WHERE (`entry`='117042' AND `GroupID`='0');
UPDATE `creature_text` SET `Text`="And for a long time, I so grumbled $g:grumbled?" WHERE (`entry`='119141' AND `GroupID`='0' AND `BroadcastTextID` ='0');
UPDATE `creature_text` SET `Text`="Let's start, $N." WHERE (`entry`='103485' AND `GroupID`='0' AND `ID`='0');
UPDATE `creature_text` SET `Text`="O great Echero, I return your bones to mother earth and pray that your spirit be in this world." WHERE (`entry`='103485' AND `GroupID`='1' AND `ID`='1');
UPDATE `creature_text` SET `Text`="Go to the Broken Shore, Karam is waiting for you there! He's exploring the area around the tomb right now." WHERE (`entry`='90463' AND `GroupID`='2');
UPDATE `creature_text` SET `Text`="It nala kanesh!" WHERE (`entry`='100169' AND `GroupID`='1');
UPDATE `creature_text` SET `Text`="An ah!" WHERE (`entry`='114071' AND `GroupID`='1');
UPDATE `creature_text` SET `Text`="It's time to start therin." WHERE (`entry`='97140' AND `GroupID`='8');
UPDATE `creature_text` SET `Text`="Nar' tala vas manari ..." WHERE (`entry`='97140' AND `GroupID`='9');
UPDATE `creature_text` SET `Text`="Tala nar' valas." WHERE (`entry`='97140' AND `GroupID`='15');
UPDATE `creature_text` SET `Text`="Go your way. I myself will get to Shal'Aran." WHERE (`entry`='102600' AND `GroupID`='10');
UPDATE `creature_text` SET `Text`="Come on! Fal'dorai dwell in the ruins below us." WHERE (`entry`='220071' AND `GroupID`='0');
UPDATE `creature_text` SET `Text`="Alien, talk to Valtrua soon!" WHERE (`entry`='107126' AND `GroupID`='4');
UPDATE `creature_text` SET `Text`="As I was afraid, the lasso is in trouble." WHERE (`entry`='107126' AND `GroupID`='5');
UPDATE `creature_text` SET `Text`="There you go, man! If you see mom, will you tell her that I have almost no skeleton keys left?" WHERE (`entry`='95893' AND `GroupID`='0');
UPDATE `creature_text` SET `Text`="Ishnu Ala, $c.May luck accompany you." WHERE (`entry`='41464' AND `GroupID`='1');
UPDATE `creature_text` SET `Text`="Your order will be ready in 5 minutes .." WHERE (`entry`='101846' AND `GroupID`='30');
UPDATE `creature_text` SET `Text`="Hey there! Yes you, $c! Overseer Shtillets against my will grabbed me and put me in this cage. Help me get out of here, and I'll explain everything." WHERE (`entry`='47900' AND `GroupID`='0');
UPDATE `creature_text` SET `Text`="Let's sleep!" WHERE (`entry`='119726' AND `GroupID`='1');
UPDATE `creature_text` SET `Text`="Glory to the Governor!" WHERE (`entry`='117480' AND `GroupID`='0');
UPDATE `creature_text` SET `Text`="Excellent. Now hurry to Xenodar! We must save Ze'ru!" WHERE (`entry`='122621' AND `GroupID`='0' AND `BroadcastTextID` ='0');
UPDATE `creature_text` SET `Text`="Hey, $N, hello! I am your personal mannequin! You can try on some morphs on me, if in doubt, is it worth buying them." WHERE (`entry`='230008' AND `GroupID`='0' AND `ID` ='0');
UPDATE `creature_text` SET `Text`="Wow!" WHERE (`entry`='230008' AND `GroupID`='1' AND `ID` ='0');
UPDATE `creature_text` SET `Text`="Oh, look, what a beauty!" WHERE (`entry`='230008' AND `GroupID`='1' AND `ID` ='1');
UPDATE `creature_text` SET `Text`="I like this outfit, and you?" WHERE (`entry`='230008' AND `GroupID`='1' AND `ID` ='2');
UPDATE `creature_text` SET `Text`="Sorry for such secrecy - an old habit. My name is Alonsy Faol. In my life I have been able to visit both the head of the church, the brainless servant of the Scourge, and the organizer of a secret war. But first of all, I have always been and remain a priest." WHERE (`entry`='102358' AND `GroupID`='3' AND `Maxtimer`='1287');
UPDATE `creature_text` SET `Text`="And according to my plan, the truly great priest should lead this council, by his actions he won the glory of the hero not only among his own, but everywhere. I believe that you are the very hero: that heroine; but you will also need to convince others of this. You are $ready:ready; to the tests?." WHERE (`entry`='102358' AND `GroupID`='3' AND `Maxtimer`='23986');
UPDATE `creature_text` SET `Text`="Will you take me a minute? I have something interesting for you here." WHERE (`entry`='112440' AND `GroupID`='3' AND `Maxtimer`='20776');
UPDATE `creature_text` SET `Text`="Make fun of her hair! This will make her angry!" WHERE (`entry`='112440' AND `GroupID`='3' AND `Maxtimer`='67789');
UPDATE `creature_text` SET `Text`="How dare you attack Mardum?" WHERE (`entry`='101943' AND `GroupID`='1' AND `BroadcastTextID` ='0');
UPDATE `creature_text` SET `Text`="Mu'shi's tears are not for the common people!" WHERE (`entry`='100427' AND `GroupID`='1' AND `BroadcastTextID` ='0');
UPDATE `creature_text` SET `Text`="Will you take me a minute? I have something interesting for you here." WHERE (`entry`='100196' AND `GroupID`='0');
UPDATE `creature_text` SET `Text`="For the Candle King!" WHERE (`entry`='97813' AND `GroupID`='1');
UPDATE `creature_text` SET `Text`="Do you need my hammer? Try to pick up.!" WHERE (`entry`='97442' AND `GroupID`='3' AND `BroadcastTextID` ='0');
UPDATE `creature_text` SET `Text`="This ancient title was once held by the oldest of the magicians of Azeroth, and it symbolizes the enormous responsibility vested in the Guardians of Tirisfal. Wear it with pride and honor." WHERE (`entry`='102700' AND `GroupID`='9');
UPDATE `creature_text` SET `Text`="Yummy! <I'm the first!>." WHERE (`entry`='95937' AND `GroupID`='1' AND `BroadcastTextID` ='0');
UPDATE `creature_text` SET `Text`="This is a trophy! I will dedicate a separate chapter to him in my new novel." WHERE (`entry`='95111' AND `GroupID`='3');
UPDATE `creature_text` SET `Text`="Useless. Stormheim climate systems block the signal." WHERE (`entry`='92932' AND `GroupID`='1');
UPDATE `creature_text` SET `Text`="Great guys! You saved your beloved captain and... hey, what are you doing ?!" WHERE (`entry`='91544' AND `GroupID`='0' AND `BroadcastTextID` ='0');
UPDATE `creature_text` SET `Text`="Earth-walkers are no match for us." WHERE (`entry`='90109' AND `GroupID`='1' AND `BroadcastTextID` ='0');
UPDATE `creature_text` SET `Text`="Oh, you $gsmall:small; $gimpudent:impudent; " WHERE (`entry`='88859' AND `GroupID`='4' AND `BroadcastTextID` ='0');
UPDATE `creature_text` SET `Text`="Talk to Dungar when you’re $gotready:ready; fly to Ashran." WHERE (`entry`='79953' AND `GroupID`='3' AND `BroadcastTextID` ='0');
UPDATE `creature_text` SET `Text`="%s absorbs the shadow energy of the enemy." WHERE (`entry`='19527' AND `GroupID`='1' AND `BroadcastTextID` ='0');
UPDATE `creature_text` SET `Text`="You don't need to understand that, Arthas. All that is required of you is to die." WHERE (`entry`='28340' AND `GroupID`='3' AND `BroadcastTextID` ='0');
UPDATE `creature_text` SET `Text`="Why are you protecting Kirin Tor ..." WHERE (`entry`='30660' AND `GroupID`='4' AND `Maxtimer`='12000');
UPDATE `creature_text` SET `Text`="WhIn place of this, other portals will arise!" WHERE (`entry`='30660' AND `GroupID`='4' AND `Maxtimer`='13000');
UPDATE `creature_text` SET `Text`="My death will not stop this invasion!" WHERE (`entry`='30660' AND `GroupID`='4' AND `Maxtimer`='18000');
UPDATE `creature_text` SET `Text`="You can't destroy this portal!" WHERE (`entry`='30660' AND `GroupID`='3' AND `Maxtimer`='4000');
