-- Antorus low pop adds scaling --

DELETE FROM `creature_difficulty_stat` WHERE `entry`=130192 AND `difficulty`=14;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (130192, 14, 2, 70);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=130192 AND `difficulty`=15;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (130192, 15, 2, 70);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=130192 AND `difficulty`=16;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (130192, 16, 2, 70);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=130192 AND `difficulty`=17;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (130192, 17, 2, 70);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=127725 AND `difficulty`=14;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (127725, 14, 3, 42);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=127725 AND `difficulty`=15;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (127725, 15, 3, 42);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=127725 AND `difficulty`=16;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (127725, 16, 3, 42);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=127725 AND `difficulty`=17;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (127725, 17, 3, 42);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=127724 AND `difficulty`=14;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (127724, 14, 3, 45);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=127724 AND `difficulty`=15;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (127724, 15, 3, 45);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=127724 AND `difficulty`=16;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (127724, 16, 3, 45);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=127724 AND `difficulty`=17;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (127724, 17, 3, 45);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=127723 AND `difficulty`=14;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (127723, 14, 2, 130);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=127723 AND `difficulty`=15;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (127723, 15, 2, 130);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=127723 AND `difficulty`=16;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (127723, 16, 2, 130);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=127723 AND `difficulty`=17;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (127723, 17, 2, 130);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=127233 AND `difficulty`=14;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (127233, 14, 1, 42);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=127233 AND `difficulty`=15;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (127233, 15, 1, 42);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=127233 AND `difficulty`=16;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (127233, 16, 1, 42);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=127233 AND `difficulty`=17;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (127233, 17, 1, 42);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=126776 AND `difficulty`=14;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (126776, 14, 1, 50);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=126776 AND `difficulty`=15;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (126776, 15, 1, 50);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=126776 AND `difficulty`=16;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (126776, 16, 1, 50);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=126776 AND `difficulty`=17;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (126776, 17, 1, 50);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=126767 AND `difficulty`=14;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (126767, 14, 1, 100);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=126767 AND `difficulty`=15;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (126767, 15, 1, 100);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=126767 AND `difficulty`=16;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (126767, 16, 1, 100);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=126767 AND `difficulty`=17;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (126767, 17, 1, 100);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=126764 AND `difficulty`=14;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (126764, 14, 1, 50);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=126764 AND `difficulty`=15;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (126764, 15, 1, 50);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=126764 AND `difficulty`=16;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (126764, 16, 1, 50);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=126764 AND `difficulty`=17;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (126764, 17, 1, 50);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=126558 AND `difficulty`=14;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (126558, 14, 1, 70);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=126558 AND `difficulty`=15;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (126558, 15, 1, 70);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=126558 AND `difficulty`=16;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (126558, 16, 1, 70);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=126558 AND `difficulty`=17;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (126558, 17, 1, 70);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=126333 AND `difficulty`=14;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (126333, 14, 1, 42);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=126333 AND `difficulty`=15;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (126333, 15, 1, 42);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=126333 AND `difficulty`=16;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (126333, 16, 1, 42);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=126333 AND `difficulty`=17;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (126333, 17, 1, 42);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=125570 AND `difficulty`=14;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (125570, 14, 1, 80);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=125570 AND `difficulty`=15;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (125570, 15, 1, 80);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=125570 AND `difficulty`=16;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (125570, 16, 1, 80);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=125570 AND `difficulty`=17;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (125570, 17, 1, 80);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=125569 AND `difficulty`=14;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (125569, 14, 1, 80);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=125569 AND `difficulty`=15;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (125569, 15, 1, 80);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=125569 AND `difficulty`=16;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (125569, 16, 1, 80);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=125569 AND `difficulty`=17;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (125569, 17, 1, 80);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=125549 AND `difficulty`=14;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (125549, 14, 0.75, 40);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=125549 AND `difficulty`=15;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (125549, 15, 0.75, 40);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=125549 AND `difficulty`=16;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (125549, 16, 0.75, 40);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=125549 AND `difficulty`=17;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (125549, 17, 0.75, 40);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=125547 AND `difficulty`=14;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (125547, 14, 0.66, 42);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=125547 AND `difficulty`=15;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (125547, 15, 0.66, 42);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=125547 AND `difficulty`=16;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (125547, 16, 0.66, 42);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=125547 AND `difficulty`=17;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (125547, 17, 0.66, 42);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=125545 AND `difficulty`=14;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (125545, 14, 0.42, 35);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=125545 AND `difficulty`=15;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (125545, 15, 0.42, 35);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=125545 AND `difficulty`=16;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (125545, 16, 0.42, 35);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=125545 AND `difficulty`=17;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (125545, 17, 0.42, 35);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=125535 AND `difficulty`=14;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (125535, 14, 1, 80);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=125535 AND `difficulty`=15;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (125535, 15, 1, 80);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=125535 AND `difficulty`=16;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (125535, 16, 1, 80);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=125535 AND `difficulty`=17;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (125535, 17, 1, 80);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=123480 AND `difficulty`=14;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (123480, 14, 2, 55);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=123480 AND `difficulty`=15;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (123480, 15, 2, 55);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=123480 AND `difficulty`=16;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (123480, 16, 2, 55);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=123480 AND `difficulty`=17;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (123480, 17, 2, 55);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=123478 AND `difficulty`=14;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (123478, 14, 1, 50);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=123478 AND `difficulty`=15;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (123478, 15, 1, 50);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=123478 AND `difficulty`=16;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (123478, 16, 1, 50);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=123478 AND `difficulty`=17;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (123478, 17, 1, 50);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=123477 AND `difficulty`=14;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (123477, 14, 2.5, 75);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=123477 AND `difficulty`=15;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (123477, 15, 2.5, 75);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=123477 AND `difficulty`=16;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (123477, 16, 2.5, 75);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=123477 AND `difficulty`=17;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (123477, 17, 2.5, 75);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=123476 AND `difficulty`=14;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (123476, 14, 2, 75);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=123476 AND `difficulty`=15;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (123476, 15, 2, 75);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=123476 AND `difficulty`=16;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (123476, 16, 2, 75);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=123476 AND `difficulty`=17;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (123476, 17, 2, 75);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=123402 AND `difficulty`=14;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (123402, 14, 2.5, 150);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=123402 AND `difficulty`=15;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (123402, 15, 2.5, 150);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=123402 AND `difficulty`=16;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (123402, 16, 2.5, 150);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=123402 AND `difficulty`=17;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (123402, 17, 2.5, 150);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=123398 AND `difficulty`=14;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (123398, 14, 2.5, 110);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=123398 AND `difficulty`=15;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (123398, 15, 2.5, 110);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=123398 AND `difficulty`=16;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (123398, 16, 2.5, 110);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=123398 AND `difficulty`=17;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (123398, 17, 2.5, 110);


-- Antorus low pop Boss scaling --

DELETE FROM `creature_difficulty_stat` WHERE `entry`=124158 AND `difficulty`=14;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (124158, 14, 0.1, 1000);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=124158 AND `difficulty`=15;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (124158, 15, 0.1, 1000);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=124158 AND `difficulty`=16;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (124158, 16, 0.1, 1000);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=124158 AND `difficulty`=17;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (124158, 17, 0.1, 1000);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=122778 AND `difficulty`=14;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (122778, 14, 1, 50);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=122778 AND `difficulty`=15;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (122778, 15, 1, 50);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=122778 AND `difficulty`=16;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (122778, 16, 1, 50);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=122778 AND `difficulty`=17;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (122778, 17, 1, 50);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=122773 AND `difficulty`=14;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (122773, 14, 1, 50);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=122773 AND `difficulty`=15;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (122773, 15, 1, 50);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=122773 AND `difficulty`=16;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (122773, 16, 1, 50);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=122773 AND `difficulty`=17;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (122773, 17, 1, 50);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=122477 AND `difficulty`=14;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (122477, 14, 1, 420);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=122477 AND `difficulty`=15;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (122477, 15, 1, 420);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=122477 AND `difficulty`=16;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (122477, 16, 1, 420);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=122477 AND `difficulty`=17;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (122477, 17, 1, 420);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=122450 AND `difficulty`=14;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (122450, 14, 2, 1000);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=122450 AND `difficulty`=15;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (122450, 15, 2, 1000);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=122450 AND `difficulty`=16;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (122450, 16, 2, 1000);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=122450 AND `difficulty`=17;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (122450, 17, 2, 1000);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=122369 AND `difficulty`=14;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (122369, 14, 1, 1000);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=122369 AND `difficulty`=15;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (122369, 15, 1, 1000);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=122369 AND `difficulty`=16;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (122369, 16, 1, 1000);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=122369 AND `difficulty`=17;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (122369, 17, 1, 1000);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=122367 AND `difficulty`=14;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (122367, 14, 1, 1000);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=122367 AND `difficulty`=15;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (122367, 15, 1, 1000);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=122367 AND `difficulty`=16;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (122367, 16, 1, 1000);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=122367 AND `difficulty`=17;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (122367, 17, 1, 1000);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=122333 AND `difficulty`=14;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (122333, 14, 1, 1000);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=122333 AND `difficulty`=15;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (122333, 15, 1, 1000);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=122333 AND `difficulty`=16;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (122333, 16, 1, 1000);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=122333 AND `difficulty`=17;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (122333, 17, 1, 1000);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=122135 AND `difficulty`=14;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (122135, 14, 1, 420);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=122135 AND `difficulty`=15;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (122135, 15, 1, 420);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=122135 AND `difficulty`=16;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (122135, 16, 1, 420);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=122135 AND `difficulty`=17;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (122135, 17, 1, 420);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=122104 AND `difficulty`=14;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (122104, 14, 1, 750);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=122104 AND `difficulty`=15;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (122104, 15, 1, 750);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=122104 AND `difficulty`=16;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (122104, 16, 1, 750);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=122104 AND `difficulty`=17;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (122104, 17, 1, 750);


-- Antorus High Command low pop adds scaling --
DELETE FROM `creature_difficulty_stat` WHERE `entry`=122890 AND `difficulty`=14;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (122890, 14, 1, 42);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=122890 AND `difficulty`=15;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (122890, 15, 1, 42);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=122890 AND `difficulty`=16;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (122890, 16, 1, 42);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=122890 AND `difficulty`=17;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (122890, 17, 1, 42);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=122718 AND `difficulty`=14;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (122718, 14, 1, 42);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=122718 AND `difficulty`=15;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (122718, 15, 1, 42);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=122718 AND `difficulty`=16;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (122718, 16, 1, 42);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=122718 AND `difficulty`=17;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (122718, 17, 1, 42);

-- Antorus Eonar low pop adds scaling --
DELETE FROM `creature_difficulty_stat` WHERE `entry`=124207 AND `difficulty`=14;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (124207, 14, 1, 35);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=124207 AND `difficulty`=15;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (124207, 15, 1, 35);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=124207 AND `difficulty`=16;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (124207, 16, 1, 35);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=124207 AND `difficulty`=17;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (124207, 17, 1, 35);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=123760 AND `difficulty`=14;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (123760, 14, 3, 60);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=123760 AND `difficulty`=15;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (123760, 15, 3, 60);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=123760 AND `difficulty`=16;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (123760, 16, 3, 60);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=123760 AND `difficulty`=17;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (123760, 17, 3, 60);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=123452 AND `difficulty`=14;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (123452, 14, 1, 42);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=123452 AND `difficulty`=15;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (123452, 15, 1, 42);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=123452 AND `difficulty`=16;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (123452, 16, 1, 42);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=123452 AND `difficulty`=17;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (123452, 17, 1, 42);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=123451 AND `difficulty`=14;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (123451, 14, 1, 30);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=123451 AND `difficulty`=15;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (123451, 15, 1, 30);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=123451 AND `difficulty`=16;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (123451, 16, 1, 30);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=123451 AND `difficulty`=17;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (123451, 17, 1, 30);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=123191 AND `difficulty`=14;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (123191, 14, 1, 25);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=123191 AND `difficulty`=15;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (123191, 15, 1, 25);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=123191 AND `difficulty`=16;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (123191, 16, 1, 25);
DELETE FROM `creature_difficulty_stat` WHERE `entry`=123191 AND `difficulty`=17;
INSERT INTO `creature_difficulty_stat` (`entry`, `difficulty`, `dmg_multiplier`, `HealthModifier`) VALUES (123191, 17, 1, 25);
