/* SYNC DB : legion_hotfixes */ 
SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ;
 START TRANSACTION;
/* SYNC TABLE : `mount` */
UPDATE `mount` SET `Name`='The Loké\'nahak Provinces', `Description`='Do you like cats?', `SourceText`='Special Project Awards', `SourceSpellID`='305190', `MountFlyRideHeight`='0', `MountTypeID`='230', `Flags`='0', `SourceTypeEnum`='2', `ID`='5016', `PlayerConditionID`='0', `UiModelSceneID`='4', `VerifiedBuild`='0'  WHERE (`ID` = 5016) ;
UPDATE `mount` SET `Name`='Zuldazar\'s Lizard', `Description`='A means of transportation to become High Priests and Zandalari Elders, adorned with exquisite harness and blessed by Rezan, the greatest of the devils.', `SourceText`='Special Project Awards', `SourceSpellID`='305194', `MountFlyRideHeight`='0', `MountTypeID`='230', `Flags`='0', `SourceTypeEnum`='2', `ID`='5020', `PlayerConditionID`='0', `UiModelSceneID`='4', `VerifiedBuild`='0'  WHERE (`ID` = 5020) ;
UPDATE `mount` SET `Name`='Kul-Tiras Horse', `Description`='Kul-Tiras horses are tamed from an early age not to be afraid of the sea and are raced along the coast in a myriad of salty splashes.', `SourceText`='Special Project Awards', `SourceSpellID`='305193', `MountFlyRideHeight`='0', `MountTypeID`='230', `Flags`='0', `SourceTypeEnum`='2', `ID`='5019', `PlayerConditionID`='0', `UiModelSceneID`='4', `VerifiedBuild`='0'  WHERE (`ID` = 5019) ;
UPDATE `mount` SET `Name`='Affected Abyss Bird of Fire', `Description`='After the connection with the abyss, the rage of these birds became even more...', `SourceText`='Special Project Awards', `SourceSpellID`='305184', `MountFlyRideHeight`='0', `MountTypeID`='230', `Flags`='0', `SourceTypeEnum`='2', `ID`='5010', `PlayerConditionID`='0', `UiModelSceneID`='4', `VerifiedBuild`='0'  WHERE (`ID` = 5010) ;
UPDATE `mount` SET `Name`='Blue Phoenix', `Description`='Birds of unprecedented beauty.', `SourceText`='Special Project Awards', `SourceSpellID`='305185', `MountFlyRideHeight`='0', `MountTypeID`='248', `Flags`='0', `SourceTypeEnum`='2', `ID`='5011', `PlayerConditionID`='0', `UiModelSceneID`='4', `VerifiedBuild`='0'  WHERE (`ID` = 5011) ;
UPDATE `mount` SET `Name`='Lilac Phoenix', `Description`='Birds of unprecedented beauty.', `SourceText`='Special Project Awards', `SourceSpellID`='305186', `MountFlyRideHeight`='0', `MountTypeID`='248', `Flags`='0', `SourceTypeEnum`='2', `ID`='5012', `PlayerConditionID`='0', `UiModelSceneID`='4', `VerifiedBuild`='0'  WHERE (`ID` = 5012) ;
UPDATE `mount` SET `Name`='Blazing phoenix', `Description`='Birds of unprecedented beauty.', `SourceText`='Special Project Awards', `SourceSpellID`='305187', `MountFlyRideHeight`='0', `MountTypeID`='248', `Flags`='0', `SourceTypeEnum`='2', `ID`='5013', `PlayerConditionID`='0', `UiModelSceneID`='4', `VerifiedBuild`='0'  WHERE (`ID` = 5013) ;
UPDATE `mount` SET `Name`='Provinces of Bad Claws', `Description`='The Blazing Legion has experimented with the desecration of many animal species. Including fire birds from volcanic worlds.', `SourceText`='Special Project Awards', `SourceSpellID`='305188', `MountFlyRideHeight`='0', `MountTypeID`='230', `Flags`='0', `SourceTypeEnum`='2', `ID`='5014', `PlayerConditionID`='0', `UiModelSceneID`='4', `VerifiedBuild`='0'  WHERE (`ID` = 5014) ;
UPDATE `mount` SET `Name`='Xuen child', `Description`='Do you like cats?', `SourceText`='Special Project Awards', `SourceSpellID`='305189', `MountFlyRideHeight`='0', `MountTypeID`='230', `Flags`='0', `SourceTypeEnum`='2', `ID`='5015', `PlayerConditionID`='0', `UiModelSceneID`='4', `VerifiedBuild`='0'  WHERE (`ID` = 5015) ;
UPDATE `mount` SET `Name`='Phantom hippogriff', `Description`='Causes the Hippogriff\'s Spirit.', `SourceText`='Special Project Awards', `SourceSpellID`='305192', `MountFlyRideHeight`='0', `MountTypeID`='248', `Flags`='0', `SourceTypeEnum`='2', `ID`='5018', `PlayerConditionID`='0', `UiModelSceneID`='4', `VerifiedBuild`='0'  WHERE (`ID` = 5018) ;
UPDATE `mount` SET `Name`='Illidari Badger', `Description`='Illidari\'s tame badass. It\'s terrible, but you can walk.', `SourceText`='Special Project Awards', `SourceSpellID`='305191', `MountFlyRideHeight`='0', `MountTypeID`='248', `Flags`='0', `SourceTypeEnum`='2', `ID`='5017', `PlayerConditionID`='0', `UiModelSceneID`='4', `VerifiedBuild`='0'  WHERE (`ID` = 5017) ;
UPDATE `mount` SET `Name`='Shu-tsen, Divine Guardian.', `Description`='While the Golden Lotus pandarans struggled to restore the Eternal Blossoming Dol, one statue came to life and silently protected them from Shah attacks. Some consider Shu-tsen a symbol of luck, others a gift of light. He will be a faithful companion to any hero who dares to defend Azeroth from the mad whispering of the ancient gods.', `SourceText`='Special Project Awards', `SourceSpellID`='305195', `MountFlyRideHeight`='0', `MountTypeID`='248', `Flags`='0', `SourceTypeEnum`='2', `ID`='5021', `PlayerConditionID`='0', `UiModelSceneID`='4', `VerifiedBuild`='0'  WHERE (`ID` = 5021) ;
/* SYNC TABLE : `mount_locale` */
UPDATE `mount_locale` SET `ID`='5000', `locale`='ruRU', `Name_lang`='Magmatic hound', `Description_lang`='Initially, these dogs were used for tracking and killing. But later they became sled dogs as well.', `SourceText_lang`='Award for New Year\'s Event 2018', `VerifiedBuild`='1'  WHERE (`ID` = 5000 AND `locale` = 'ruRU') ;
UPDATE `mount_locale` SET `ID`='5001', `locale`='ruRU', `Name_lang`='Taresgosa\'s appearance', `Description_lang`='The strength of the staff is no longer required. You can take the look of Taresgosa at any time.', `SourceText_lang`='Special Project Awards.', `VerifiedBuild`='1'  WHERE (`ID` = 5001 AND `locale` = 'ruRU') ;
UPDATE `mount_locale` SET `ID`='5010', `locale`='ruRU', `Name_lang`='Affected abyss bird of fire', `Description_lang`='After the connection with the abyss, the rage of these birds became even more...', `SourceText_lang`='Special Project Awards', `VerifiedBuild`='1'  WHERE (`ID` = 5010 AND `locale` = 'ruRU') ;
UPDATE `mount_locale` SET `ID`='5011', `locale`='ruRU', `Name_lang`='Blue Phoenix', `Description_lang`='Birds of unprecedented beauty.', `SourceText_lang`='Special Project Awards', `VerifiedBuild`='1'  WHERE (`ID` = 5011 AND `locale` = 'ruRU') ;
UPDATE `mount_locale` SET `ID`='5012', `locale`='ruRU', `Name_lang`='Lilac phoenix', `Description_lang`='Birds of unprecedented beauty.', `SourceText_lang`='Special Project Awards', `VerifiedBuild`='1'  WHERE (`ID` = 5012 AND `locale` = 'ruRU') ;
UPDATE `mount_locale` SET `ID`='5013', `locale`='ruRU', `Name_lang`='Blazing phoenix', `Description_lang`='Birds of unprecedented beauty.', `SourceText_lang`='Special Project Awards', `VerifiedBuild`='1'  WHERE (`ID` = 5013 AND `locale` = 'ruRU') ;
UPDATE `mount_locale` SET `ID`='5014', `locale`='ruRU', `Name_lang`='Provinces of bad claws', `Description_lang`='The Blazing Legion has experimented with the desecration of many animal species. Including fire birds from volcanic worlds.', `SourceText_lang`='Special Project Awards', `VerifiedBuild`='1'  WHERE (`ID` = 5014 AND `locale` = 'ruRU') ;
UPDATE `mount_locale` SET `ID`='5015', `locale`='ruRU', `Name_lang`='Xuen child', `Description_lang`='Do you like cats?', `SourceText_lang`='Special Project Awards', `VerifiedBuild`='1'  WHERE (`ID` = 5015 AND `locale` = 'ruRU') ;
UPDATE `mount_locale` SET `ID`='5016', `locale`='ruRU', `Name_lang`='The Loké\'nahak Provinces', `Description_lang`='Do you like cats?', `SourceText_lang`='Special Project Awards', `VerifiedBuild`='1'  WHERE (`ID` = 5016 AND `locale` = 'ruRU') ;
UPDATE `mount_locale` SET `ID`='5017', `locale`='ruRU', `Name_lang`='Illidari Badger', `Description_lang`='Illidari\'s tame badass. It\'s terrible, but you can walk.', `SourceText_lang`='Special Project Awards', `VerifiedBuild`='1'  WHERE (`ID` = 5017 AND `locale` = 'ruRU') ;
UPDATE `mount_locale` SET `ID`='5018', `locale`='ruRU', `Name_lang`='Phantom hippogriff', `Description_lang`='Causes the hippogriff\'s spirit.', `SourceText_lang`='Special Project Awards', `VerifiedBuild`='1'  WHERE (`ID` = 5018 AND `locale` = 'ruRU') ;
UPDATE `mount_locale` SET `ID`='5019', `locale`='ruRU', `Name_lang`='Kul-Tiras Horse', `Description_lang`='Kul-Tiras horses are tamed from an early age not to be afraid of the sea and are raced along the coast in a myriad of salty splashes.', `SourceText_lang`='Special Project Awards', `VerifiedBuild`='1'  WHERE (`ID` = 5019 AND `locale` = 'ruRU') ;
UPDATE `mount_locale` SET `ID`='5020', `locale`='ruRU', `Name_lang`='Zuldazar\'s Lizard', `Description_lang`='A means of transportation to become High Priests and Zandalari Elders, adorned with exquisite harness and blessed by Rezan, the greatest of the devils.', `SourceText_lang`='Special Project Awards', `VerifiedBuild`='1'  WHERE (`ID` = 5020 AND `locale` = 'ruRU') ;
UPDATE `mount_locale` SET `ID`='5021', `locale`='ruRU', `Name_lang`='Shu-tsen, Divine Guardian.', `Description_lang`='While the Golden Lotus pandarans struggled to restore the Eternal Blossoming Dol, one statue came to life and silently protected them from Shah attacks. Some consider Shu-tsen a symbol of luck, others a gift of light. He will be a faithful companion to any hero who dares to defend Azeroth from the mad whispering of the ancient gods.', `SourceText_lang`='Special Project Awards', `VerifiedBuild`='1'  WHERE (`ID` = 5021 AND `locale` = 'ruRU') ;
UPDATE `mount_locale` SET `ID`='5022', `locale`='ruRU', `Name_lang`='Dark Dawn', `Description_lang`='', `SourceText_lang`='New Year\'s Eve 2019', `VerifiedBuild`='1'  WHERE (`ID` = 5022 AND `locale` = 'ruRU') ;
UPDATE `mount_locale` SET `ID`='5023', `locale`='ruRU', `Name_lang`='Illidari Red Badger', `Description_lang`='', `SourceText_lang`='New Year\'s Eve 2019', `VerifiedBuild`='1'  WHERE (`ID` = 5023 AND `locale` = 'ruRU') ;
UPDATE `mount_locale` SET `ID`='5025', `locale`='ruRU', `Name_lang`='Taresgosa\'s appearance', `Description_lang`='The strength of the staff is no longer required. You can take the look of Taresgosa at any time.', `SourceText_lang`='Special Project Awards', `VerifiedBuild`='1'  WHERE (`ID` = 5025 AND `locale` = 'ruRU') ;
/* SYNC TABLE : `spell_effect` */
DELETE FROM `spell_effect` WHERE  `ID` IN ('73821', '72850', '72849', '72851');
INSERT INTO `spell_effect` (`ID`, `Effect`, `EffectBasePoints`, `EffectIndex`, `EffectAura`, `DifficultyID`, `EffectAmplitude`, `EffectAuraPeriod`, `EffectBonusCoefficient`, `EffectChainAmplitude`, `EffectChainTargets`, `EffectDieSides`, `EffectItemType`, `EffectMechanic`, `EffectPointsPerResource`, `EffectRealPointsPerLevel`, `EffectTriggerSpell`, `EffectPosFacing`, `EffectAttributes`, `BonusCoefficientFromAP`, `PvpMultiplier`, `Coefficient`, `Variance`, `ResourceCoefficient`, `GroupSizeBasePointsCoefficient`, `EffectSpellClassMask1`, `EffectSpellClassMask2`, `EffectSpellClassMask3`, `EffectSpellClassMask4`, `EffectMiscValue1`, `EffectMiscValue2`, `EffectRadiusIndex1`, `EffectRadiusIndex2`, `ImplicitTarget1`, `ImplicitTarget2`, `SpellID`, `VerifiedBuild`) VALUES 
('73821', '28', '0', '1', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0', '0', '0', '1', '0', '0', '0', '0', '734360', '64', '8', '0', '41', '0', '73817', '0'),
('72850', '28', '0', '1', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0', '0', '0', '1', '0', '0', '0', '0', '73436', '64', '8', '0', '41', '0', '72070', '0'),
('72849', '3', '0', '0', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '38', '0', '72070', '0'),
('72851', '63', '1', '2', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', '13', '18', '8', '72070', '0');
