/* Fotfixes*/
DELETE FROM `broadcast_text` WHERE `ID` IN ('1001001','1001002','1001003','1001004','1001005','1001006');
INSERT INTO `broadcast_text` (`ID`, `Text`, `Text1`, `EmoteID1`, `EmoteID2`, `EmoteID3`, `EmoteDelay1`, `EmoteDelay2`, `EmoteDelay3`, `EmotesID`, `LanguageID`, `Flags`, `ConditionID`, `SoundEntriesID1`, `SoundEntriesID2`, `VerifiedBuild`) VALUES ('1001001', 'Saludos, $c. Estoy en busca de los guerreros más fuertes de Azeroth para aportarles un poco de mi fuerza y riquezas, y asi apoyar la causa contra la Legion Ardiente. Pero antes necesito comprobar si eres digno de mi respeto.', NULL, '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0');
INSERT INTO `broadcast_text` (`ID`, `Text`, `Text1`, `EmoteID1`, `EmoteID2`, `EmoteID3`, `EmoteDelay1`, `EmoteDelay2`, `EmoteDelay3`, `EmotesID`, `LanguageID`, `Flags`, `ConditionID`, `SoundEntriesID1`, `SoundEntriesID2`, `VerifiedBuild`) VALUES ('1001002', 'Realmente eres digno de admirar  $c. Voy a realizar un torneo nacional para encontrar al heroe mas fuerte de cada especialización . Deseas participar en el Torneo de Sangre y Vida en la especialización actual ?\r\n', NULL, '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0');
INSERT INTO `broadcast_text` (`ID`, `Text`, `Text1`, `EmoteID1`, `EmoteID2`, `EmoteID3`, `EmoteDelay1`, `EmoteDelay2`, `EmoteDelay3`, `EmotesID`, `LanguageID`, `Flags`, `ConditionID`, `SoundEntriesID1`, `SoundEntriesID2`, `VerifiedBuild`) VALUES ('1001003', 'El Torneo de Sangre y Vida consiste en lo siguiente: $B$BCada participante deberá demostrar ante todos de lo que es capaz. Al comenzar el evento se llamaran a los participantes según el orden de inscripción. Cada participante tendrá 30 segundos para presentarse o seras descalificado y otros 20 segundos para demostrar todo su poder. Y así sucesivamente hasta finalizar el evento. $B$B Los ganadores de cada especializaciones de daño y sanación recibirán a partes iguales el dinero recaudado en las suscripciones. Los ganadores generales no recibiran ninguna recompensa extra dado que las especializaciones no se pueden comparar por las diferentes mecanicas que estas poseen. Tendrás 5 días para preparase a partir de hoy. Shunlok los estara esperando en la Arena de Gurubashi el dia del Torneo. $B$BPD: La suscripción tendrá un costo de 1000 de oro.', '', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0');
INSERT INTO `broadcast_text` (`ID`, `Text`, `Text1`, `EmoteID1`, `EmoteID2`, `EmoteID3`, `EmoteDelay1`, `EmoteDelay2`, `EmoteDelay3`, `EmotesID`, `LanguageID`, `Flags`, `ConditionID`, `SoundEntriesID1`, `SoundEntriesID2`, `VerifiedBuild`) VALUES ('1001004', 'Ya has aceptado la mision y te has inscrito en el Torneo de Sangre y Vida.', NULL, '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0');
INSERT INTO `broadcast_text` (`ID`, `Text`, `Text1`, `EmoteID1`, `EmoteID2`, `EmoteID3`, `EmoteDelay1`, `EmoteDelay2`, `EmoteDelay3`, `EmotesID`, `LanguageID`, `Flags`, `ConditionID`, `SoundEntriesID1`, `SoundEntriesID2`, `VerifiedBuild`) VALUES ('1001005', 'Ya has sido inscrito para el torneo. Para participar debes tener la quest correspondiente, por favor aceptala y no la pierdas.', NULL, '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0');
INSERT INTO `broadcast_text` (`ID`, `Text`, `Text1`, `EmoteID1`, `EmoteID2`, `EmoteID3`, `EmoteDelay1`, `EmoteDelay2`, `EmoteDelay3`, `EmotesID`, `LanguageID`, `Flags`, `ConditionID`, `SoundEntriesID1`, `SoundEntriesID2`, `VerifiedBuild`) VALUES ('1001006', 'Felicitaciones héroe y gracias por participar en el evento, recibe esta recompensa por tu esfuerzo y valor.', NULL, '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0');

SET @ITEMGUID = 505050;
REPLACE INTO `item_sparse` (`ID`, `AllowableRace`, `Display`, `Display1`, `Display2`, `Display3`, `Description`, `Flags1`, `Flags2`, `Flags3`, `Flags4`, `PriceRandomValue`, `PriceVariance`, `VendorStackCount`, `BuyPrice`, `SellPrice`, `RequiredAbility`, `MaxCount`, `Stackable`, `StatPercentEditor1`, `StatPercentEditor2`, `StatPercentEditor3`, `StatPercentEditor4`, `StatPercentEditor5`, `StatPercentEditor6`, `StatPercentEditor7`, `StatPercentEditor8`, `StatPercentEditor9`, `StatPercentEditor10`, `StatPercentageOfSocket1`, `StatPercentageOfSocket2`, `StatPercentageOfSocket3`, `StatPercentageOfSocket4`, `StatPercentageOfSocket5`, `StatPercentageOfSocket6`, `StatPercentageOfSocket7`, `StatPercentageOfSocket8`, `StatPercentageOfSocket9`, `StatPercentageOfSocket10`, `ItemRange`, `BagFamily`, `QualityModifier`, `DurationInInventory`, `DmgVariance`, `AllowableClass`, `ItemLevel`, `RequiredSkill`, `RequiredSkillRank`, `MinFactionID`, `ItemStatValue1`, `ItemStatValue2`, `ItemStatValue3`, `ItemStatValue4`, `ItemStatValue5`, `ItemStatValue6`, `ItemStatValue7`, `ItemStatValue8`, `ItemStatValue9`, `ItemStatValue10`, `ScalingStatDistributionID`, `ItemDelay`, `PageID`, `StartQuestID`, `LockID`, `RandomSelect`, `ItemRandomSuffixGroupID`, `ItemSet`, `ZoneBound`, `InstanceBound`, `TotemCategoryID`, `SocketMatch_Enchantment_Id`, `GemProperties`, `LimitCategory`, `RequiredHoliday`, `RequiredTransmogHoliday`, `ItemNameDescriptionID`, `OverallQualityID`, `InventoryType`, `RequiredLevel`, `RequiredPVPRank`, `RequiredPVPMedal`, `MinReputation`, `ContainerSlots`, `StatModifierBonusStat1`, `StatModifierBonusStat2`, `StatModifierBonusStat3`, `StatModifierBonusStat4`, `StatModifierBonusStat5`, `StatModifierBonusStat6`, `StatModifierBonusStat7`, `StatModifierBonusStat8`, `StatModifierBonusStat9`, `StatModifierBonusStat10`, `DamageDamageType`, `Bonding`, `LanguageID`, `PageMaterialID`, `Material`, `SheatheType`, `SocketType1`, `SocketType2`, `SocketType3`, `SpellWeightCategory`, `SpellWeight`, `ArtifactID`, `ExpansionID`, `VerifiedBuild`) VALUES
(@ITEMGUID,'-1','Recompensa del Torneo de Sangre y Vida',NULL,NULL,NULL,'|cff00FF00Obtienes 5 monedas para la tienda de juego y un porciento del dinero recaudado en las suscripciones.|r','134217760','0','0','0','0','0','0','0','0','0','0','1','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','-1','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','6','0','-1','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','1','0','0','0','0','0','0','0','0','0','0','0','0');

REPLACE INTO hotfix_data (`Id`, `TableHash`, `RecordId`, `Deleted`) VALUES 
(@ITEMGUID, 2442913102, @ITEMGUID, 0),
(@ITEMGUID, 1344507586, @ITEMGUID, 0),
(@ITEMGUID, 1109793673, @ITEMGUID, 0),
(@ITEMGUID, 3834752085, @ITEMGUID, 0),
(@ITEMGUID, 1073915313, @ITEMGUID, 0);
REPLACE INTO item_appearance (`ID`, `ItemDisplayInfoID`, `DefaultIconFileDataID`, `UIOrder`, `DisplayType`, `VerifiedBuild`) VALUES 
(@ITEMGUID, 0, 0, 0, 0, 0);
REPLACE INTO item_modified_appearance (`ItemID`, `ItemAppearanceID`, `ItemAppearanceModifierID`, `OrderIndex`, `TransmogSourceTypeEnum`, `ID`, `VerifiedBuild`) VALUES 
(@ITEMGUID, 0, 0, 0, 0, @ITEMGUID, 0);
REPLACE INTO item (`ID`, `IconFileDataID`, `ClassID`, `SubClassID`, `SoundOverrideSubclass`, `Material`, `InventoryType`, `SheatheType`, `ItemGroupSoundsID`, `VerifiedBuild`) VALUES 
(@ITEMGUID, 1455894, 0, 0, 0, 0, 0, 0, 0, 0); 
REPLACE INTO `item_effect` (`ID`, `SpellID`, `CoolDownMSec`, `CategoryCoolDownMSec`, `Charges`, `SpellCategoryID`, `ChrSpecializationID`, `LegacySlotIndex`, `TriggerType`, `ItemID`, `VerifiedBuild`) VALUES
(@ITEMGUID,18282,0,0,0,0,0,0,0,@ITEMGUID,0);